### ISSUE TITLE
Template 4.88: editorial change required "Code Table 2.248 -> Code Table 4.248"

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#107]
# Branch

https://github.com/wmo-im/GRIB2/tree/issue107

# Summary and purpose

This issue captures a change needed to correct a typo in Template 4.88

# Action proposed

...

# Discussions

The template 4.88 contains a typo: The octet 27 should refer to Code Table 4.248 and not to Code Table 2.248

# Detailed proposal

Correct the typo through an editorial change and include this in the current Fast Track.

**Comment by sebvi** [comment]
@amilan17 : Could you please create a branch for this issue? Thanks!

**Comment by jitsukoh** [comment]
@amilan17 @sebvi I confirm that the proposal (correction) is finalized and the branch is updated accordingly. the issue is moved to the validated status.
