### ISSUE TITLE
4.5 17/18 Definition Clarification 

### ISSUE THREAD

**Issue by marqh** [wmo-im/GRIB2#111]
Hello GRIB maintainers

within the latest PDF document version of the manual on codes that i could find:
https://library.wmo.int/index.php?lvl=notice_display&id=10684#.X18yfpMza3I
p184
```
Code table 4.5 – Fixed surface types and units
...
17–19 Reserved
...
```
states that code figure 17 & 18 are reserved

in the latest ZIP of machine processable content for v27 of GRIB2 tables:
https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version

GRIB2_CodeFlag_4_5_CodeTable_en.csv states
```
...
Fixed surface types and units,,17,,Departure level of the most unstable parcel of air (MUDL),,-,Operational
Fixed surface types and units,,18,,Departure level of a mixed layer parcel of air with specified layer depth,,Pa,Operational
Fixed surface types and units,,19,,Reserved,,,Operational
...
```
indicating that 17 & 18 are assigned and 19 reserved

is this inconsistency an editorial mistake?

How can I confidently resolve this discrepancy between the published manual and the provided tabular content please?

many thanks
mark

**Comment by marqh** [comment]
@mgange659 @richardweedon @tpowellmeto

**Comment by marqh** [comment]
@amilan17 
Anna; is this something that you may be able to provide comment or perspective on for us?

many thanks
mark

**Comment by amilan17** [comment]
[**@mgange659**](https://github.com/mgange659) [**@richardweedon**](https://github.com/richardweedon) [**@tpowellmeto**](https://github.com/tpowellmeto) @marqh 

In this case, the machine readable codes are more up-to-date than the published version of the MoC. These amendments were introduced sometime in the last year and they will be published with the new release of the MoC PDF (probably by the end of this month.) The challenge is that WMO adopts proposals, but there is a gap between adoption and publication. Therefore, starting with the submission of FT2021-2, I will provide a non-normative, yet more recent, version of the manual that includes all of the amendments. It can be used as a reference until the manual is republished. You can also go to [https://community.wmo.int/activity-areas/wis/manuals-and-guides/wis-manuals](https://community.wmo.int/activity-areas/wis/manuals-and-guides/wis-manuals) to see the status of current amendments, review the content or dig into the amendment archive. I hope this was helpful.

**Comment by amilan17** [comment]
@marqh -- will you confirm that this is no longer an issue? The draft of MoC vI.2 and the [release candidate](https://github.com/wmo-im/GRIB2/releases/tag/v28) (v28) of the machine readable codes should be in alignment.

**Comment by marqh** [comment]
i agree that this issue is resolved
