### ISSUE TITLE
Fix Typo in PDT 4.53 and 4.54

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#113]
# Summary and purpose

Typo in Product definition template 4.53 and Product definition template 4.54. 

Note says "see Code table 4.PTN..".

**Comment by amilan17** [comment]
see Attachment IV - Definition of "tiles" with time dependent attributes

**Comment by amilan17** [comment]
Sibylle and Sebastien can help

**Comment by sebvi** [comment]
I have checked the original proposal (From IPET-DRC-IV, document 2.2_5).
There is a table in the proposal called 4.233 but in the actual manual on code 4.233 is something else (aerosol type). I suspect a clash between 2 proposals during that fast track and it eventually became 4.234 (and the template originally numbered 4.52 and 4.53 became 4.53 and 4.54). 
I suspect it is that table 4.234 that should be referenced by the templates but we should check with @efucile as he was the proposer of the templates at the time.

**Comment by SibylleK** [comment]
Dear @amilan17,  I think "4.PTN" is intended and not a typo, as PTN should be defined in octet 12 in PDT 4.53 or 4.54 and could be either 234 - "Canopy cover fraction" or 236  - "Soil texture fraction".

**Comment by efucile** [comment]
Yes @SibylleK you are right. The template was generalised and the Partition Table Number is in octet 12. This is not a typo.

**Comment by amilan17** [comment]
@efucile @SibylleK does it make sense to replace 4.PTN with Code table 4.234 and Code table 4.236? I ask, because we recently introduced a way in GitHub to reference the code tables in a column. As displayed in the image below. 

![](https://user-images.githubusercontent.com/5168866/141309364-879579d1-15c4-47eb-93a1-68839bd80ac8.png)

**Comment by amilan17** [comment]
[**@efucile**](https://github.com/efucile) [**@SibylleK**](https://github.com/SibylleK) Can you please respond to my question above? I'd like to finalize this for FT22-1 within a week.

**Comment by sebvi** [comment]
I think the answer was given in an email: the product definition templates are correct because the table 4.PTN is not predetermined. I can try to dig the email with @efucile comments.

**Comment by amilan17** [comment]
no changes needed in CSV or PDF
