### ISSUE TITLE
code table 4.2: New parameters for thermal discomfort indexes

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#119]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue119
# Summary and purpose

The purpose of this proposal is to extend the range of thermal discomfort indexes added in the recent years under the new discipline 20.

# Action proposed

The team is invited to review and approve the proposal

# Discussions

In the recent years and in the context of global warming, the popularity of thermal discomfort indexes have been increasing. ECMWF has been asked to compute and disseminate several of these indexes. In this proposal we request  new indexes and auxiliary parameters used to compute the indexes.

 ~~**Wet Bulb Globe Temperature From MRT** is an approximation of the ISO WBGT. It incorporates MRT to calculate the Globe Temperature component of WBGT, with a widely accepted Wet Bulb Temperature empirical expression (Stull, 2011) to allow numerical weather prediction services to provide the ISO where instrument observation needed are sparse.
This new parameter is similar to existing WBGT (discipline 20, category 0, entry 2) but uses Mean Radiant Temperature (discipline 20, category 0, entry 1) instead of the one used in the original definition.~~

 **Humidex** is a heat index that combines temperature with relative humidity, it was originally developed by the Canadian Met Service. Humidity is an important aspect of thermal comfort effecting how the body thermoregulates. see Masterson J, Richardson FA. Humidex, A Method of Quantifying Human Discomfort Due to Excessive Heat and Humidity. Downsview, Ontario: Environment Canada; 1979.

**Effective Temperature** is the temperature felt by the human organism for certain values of meteorological parameters such as air temperature, relative humidity of air, and wind speed, which determine the thermal exchange between the organism and the environment (as defined in Missenard FA (1933) Température effective d’une atmosphere Généralisation température résultante d’un milieu. In: Encyclopédie Industrielle et Commerciale, Etude physiologique et technique de la ventilation. Librerie de l’Enseignement Technique, Paris, pp 131–185)

**Normal effective Temperature** is a modification of the above Effective temperature as defined in Li PW, Chan ST. Application of a weather stress index for alerting the public to stressful weather in Hong Kong. Meteorol Appl. 2000;7:369–375. doi: 10.1017/S1350482700001602.

**Standard  Effective Temperature** is defined as the equivalent dry bulb temperature of an isothermal environment at 50% relative humidity in which a subject, while wearing clothing standardized for activity concerned, would have the same heat stress (skin temperature) and thermoregulatory strain (skin wettedness) as in the actual test environment.

**Physiological Equivalent Temperature** is based on a complete heat budget model of the human body. It provides the equivalent temperature of a isothermal reference environment with a water vapor pressure of 12 hPa (50% at 20°C) and light air (0.1 m s−1), at which the heat balance of a reference person is maintained with core and skin temperature equal to those under the conditions being assessed. see Höppe P. Int J Biometeorol. 1999 Oct; 43(2):71-5.

**Saturation Water Vapour Pressure** is defined as the vapor pressure of a system, at a given temperature, for which the vapor of a substance is in equilibrium with a plane surface of that substance's pure liquid or solid phase; that is, the vapor pressure of a system that has attained saturation but not supersaturation.

# Detailed proposal

add in code table 4.2 discipline 0 category 3
| code | Name | Units |
|--|--|--|
| 32 | Saturation Water Vapour Pressure | Pa|

add in code table 4.2 discipline 20, category 0

| code | Name | Units |
|--|--|--|
| 3 | ~~Wet Bulb Globe Temperature From MRT~~ Globe Temperature | K |
| 4 | Humidex | K |
| 5 | Effective Temperature | K |
| 6 | Normal Effective Temperature | K |
| 7 | Standard Effective Temperature | K |
| 8 |  Physiological Equivalent Temperature | K |

**Comment by sebvi** [comment]
branch updated

**Comment by amilan17** [comment]
needs validation - Tom may have colleagues who respond.

**Comment by tomkralidis** [comment]
Hi @sebvi relaying some comments from MSC experts:

Is there any reference for the simplified WBGT computation suggested? We assume it is from Liljegren (2008) ?

Are there similarities between discipline 20/category 0/code 2 (Wet-bulb globe temperature) and the proposed code 3?

1. "to allow numerical weather prediction services to provide the ISO where instrument observation needed are sparse."   

Is the idea that we would have one variable for models and one for measurements?

Should each organization provides its own code for its WBGT calculation?

2. "It incorporates MRT to calculate the Globe Temperature component"

I think it is more of less explicitly the case for all organizations formulation that are physically-based (in contrary to statistics).  

The globe temperature is computed from explicitly modelled MRT in Canada.

Idea : only separate physically-based versus statistically-based formulations. Or keep one code only for WBGT.

In addition, it would seem relevant to add the globe temperature (GT) in discipline 20/category 0.   It is highly possible that there will be more direct measurements in the future (but not urgent).

(recall : WBGT = 0.7 NWB + 0.2 GT  + 0.1 T)

**Comment by sebvi** [comment]
oh I forgot to answer @tomkralidis 's comment!

After consulting our in-house experts we agree that the variant of WBGT we are proposing is indeed very similar to existing WBGT (code 2): If Canada is using entry 2 to store what we intent to compute and store in the proposed entry 3, then it is unnecessary to create a new entry an potentially confused user. We will make clear in the accompanying documentation of our parameter how it is exactly computed.

We also welcome the suggestion of adding Globe Temperature GT. Consequently, **I will edit the original proposal, remove the proposed content of entry 3 and reassign it to Globe Temperature.** 

We really need this proposal to go through as we have already started to produce the data, we can't wait until next "fast" track!

**Comment by sebvi** [comment]
I have updated the branch accordingly

**Comment by amilan17** [comment]
https://github.com/wmo-im/GRIB2/compare/93853f785861d43e2d9dcfa73a18801ca44f90d3..e853b7be00ca0da28c4de03ba64998c038b1e057

**Comment by amilan17** [comment]
> I have updated the branch accordingly

Thanks! I made some words lower case for editorial consistency.

**Comment by jitsukoh** [comment]
@sebvi @amilan17 thank you for updating the branch. I confirm that the branch is updated and the issue is moved to the validated status.
