### ISSUE TITLE
add new wave parameters to code table 4.2

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#121]
# Branch
https://github.com/wmo-im/GRIB2/tree/iss121
# Summary and purpose

ECMWF is requesting 2 new parameters for wave modelling.

# Action proposed

The team is invited to review the proposal and approve it for publication in the next release of the manual on Codes.

# Discussions

ECMWF is requesting 2 new parameter in code Table 4.2 discipline 10, category 0 to support wave modelling.

**Peak direction of total swell** 
it seems this component is missing in the list of parameter in discipline 10, category 0

**Whitecap fraction** 
Breaking waves appearing in the form of whitecaps represent a very familiar yet poorly understood feature of the wind-driven sea surface. They are formed when large numbers of bubbles produced by a wave rise to the surface, and the bright white area of a whitecap arises from multiple light scattering by elements of size comparable to or greater than the wavelength of visible light. These elements are clusters of proximate, closely packed bubbles at or near the surface.

# Detailed proposal

add in code table 4.2 discipline 10, category 0

| code | Meaning | Units|
|--|--|--|
| 72 | Peak direction of total swell | degree true |
|73 | Whitecap fraction | fraction|

**Comment by sebvi** [comment]
branch updated

**Comment by jitsukoh** [comment]
@sebvi @amilan17 I confirm that the branch is updated and this issue was moved to the validated status.
