### ISSUE TITLE
Wrong reserved range for table 4.2 and "Product discipline 0 - Meteorological products, parameter category 1: moisture"

### ISSUE THREAD

**Issue by rouault** [wmo-im/GRIB2#129]
# Branch

https://github.com/wmo-im/GRIB2/tree/issue129

# Summary and purpose

In table https://raw.githubusercontent.com/wmo-im/GRIB2/master/GRIB2_CodeFlag_4_2_CodeTable_en.csv, there are the following records:

```
Parameter number by product discipline and parameter category,"Product discipline 0 - Meteorological products, parameter category 1: moisture",149,,Cloud water mixing ratio,,kg kg-1,Operational
Parameter number by product discipline and parameter category,"Product discipline 0 - Meteorological products, parameter category 1: moisture",149-191,,Reserved,,,Operational
```

The range 149-191 conflicts with the previous record

# Action proposed

Change range 149-191 to 150-191

**Comment by amilan17** [comment]
@jitsukoh This was a typo. Please validate the edit [https://github.com/wmo-im/GRIB2/compare/FT22-1...issue129](https://github.com/wmo-im/GRIB2/compare/FT22-1...issue129)

**Comment by amilan17** [comment]
@rouault Thanks for letting us know.

**Comment by jitsukoh** [comment]
@amilan17 I confirm that the CSV file was corrected and the issue is moved to the validated status.

**Comment by jitsukoh** [comment]
@amilan17 I found a "different" typo in the same table in the PDF version (I am looking at 306_I2_2019_updated 2021_en_july.pdf). 
"Reserved" figures should be **150**-191.
<img width="449" alt="GRIB4 2-0-1" src="https://user-images.githubusercontent.com/62408376/145913893-e2f31723-4604-460f-af1a-d98e394e34d9.PNG">
At this moment, I moved this back to in validation.

**Comment by amilan17** [comment]
@jitsukoh if I understand correctly, the error in the CSV is the same as the error in the PDF. The CSV is now correct and the PDF will be corrected at the same time as the other amendments.

**Comment by jitsukoh** [comment]
@amilan17 thanks. The CSV said "149-191" but the PDF said "147-191" but the wrong part is the same. Moved to validated again.
