### ISSUE TITLE
Mistake in Flag table 3.4 - scanning mode

### ISSUE THREAD

**Issue by shahramn** [wmo-im/GRIB2#144]
The entry:
Adjacent rows scans in the opposite direction
should read:
Adjacent rows **scan** in the opposite direction

**Comment by shahramn** [comment]
This should be a very easy fix ;)

**Comment by amilan17** [comment]
@amilan17 create branch

**Comment by marijanacrepulja** [comment]
@amilan17 thanks! I confirm that the branch is updated and moved it to the validated status.
