### ISSUE TITLE
Categories 8-12 are defined in Common Code Table 4.1 but are not used in Code Table 4.2

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#157]
# Summary and purpose

Enter text.

# Action proposed

Enter text.

# Discussions

I was planning to assign a new category to 8 ... until I realized we somehow have an inconsistency: We don't have any entries in Code Table 4.2 for categories 8 to 12 (this is why I chose 8 for my new categry) but we actually have those number assigned in Code Table 4.1 (although entries 9-12 are marked as deprecated .... but not entry 8!!!):

Parameter category by product discipline,Product discipline 0 - Meteorological products,8,,Kinematic stability indices,,,,Operational  
Parameter category by product discipline,Product discipline 0 - Meteorological products,9,,Temperature probabilities,,,,Deprecated  
Parameter category by product discipline,Product discipline 0 - Meteorological products,10,,Moisture probabilities,,,,Deprecated  
Parameter category by product discipline,Product discipline 0 - Meteorological products,11,,Momentum probabilities,,,,Deprecated  
Parameter category by product discipline,Product discipline 0 - Meteorological products,12,,Mass probabilities,,,,Deprecated

I have checked in earlier version of the Code Tables (I checked version 5) and we don't seem to have ever populated this category 8.

# Detailed proposal

|Title\_en                                |SubTitle\_en                                   |CodeFlag|Value|MeaningParameterDescription\_en|Note\_en|noteIDs|UnitComments\_en|Status    |  
|----------------------------------------|----------------------------------------------|--------|-----|------------------------------|-------|-------|---------------|----------|  
|Parameter category by product discipline|Product discipline 0 - Meteorological products|8       |     |Kinematic stability indices   | (see Note)      |  46     |               |~Operational~Deprecated|  
|Parameter category by product discipline|Product discipline 0 - Meteorological products|9       |     |Temperature probabilities     |(see Note)       |   46    |               |Deprecated|  
|Parameter category by product discipline|Product discipline 0 - Meteorological products|10      |     |Moisture probabilities        |  (see Note)     |    46   |               |Deprecated|  
|Parameter category by product discipline|Product discipline 0 - Meteorological products|11      |     |Momentum probabilities        |(see Note)       |    46  |               |Deprecated|  
|Parameter category by product discipline|Product discipline 0 - Meteorological products|12      |     |Mass probabilities            |    (see Note)   |   46    |               |Deprecated|

Note:
46,"Entries ~9, 10, 11 and 12~ 8 - 12 are deprecated."

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022.)  meeting notes: 

Decision: change category 8 to deprecated and don't re-use.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@marijanacrepulja will validate

**Comment by marijanacrepulja** [comment]
@amilan17 it looks good, many thanks.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT
