### ISSUE TITLE
GRIB2_Template_4_91_ProductDefinitionTemplate_en.csv: Possible off-by-one error in description

### ISSUE THREAD

**Issue by manfredsc** [wmo-im/GRIB2#166]
### Details

In entry (line) 40 of GRIB2_Template_4_91_ProductDefinitionTemplate_en.csv,
there seems to be an off-by-one error in the description (Contents_en).

The original description is
`72-nn These octets are included only if n > 1, where nn = 72+12(n-1)+12(NC-1)`
I think this should be
`72-nn These octets are included only if n > 1, where nn = 71+12(n-1)+12(NC-1)`
because if N==1 and NC==1, this results in nn=72, so the depicted octet range is 72-72, which is 1 byte wide,
which does not make sense.
The proposed change would also be in line with the following entry (line 41),
which has `(72+12(NC-1))-(83+12(NC-1))` as OctetNo value, i.e. an odd end value.
With the original formulation, all end values would be supposed to have even values.

### Requestor

Manfred Schwarb, schwarb@meteodat.ch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-22.9.2022:](https://github.com/wmo-im/CCT/wiki/Teleconference-22.9.2022:) @sebvi will look at it, it's probably just a typo.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022.)  meeting notes: 

@sebvi looked at it. @amilan17 create a branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes:

@amilan17 will work on

**Comment by sebvi** [comment]
I can update the branch by the end of the week.

**Comment by sebvi** [comment]
I have updated the branch in my local copy of the repo but I have troubled to upload it...

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

branch will be updated asap

**Comment by amilan17** [comment]
change made in this branch: https://github.com/wmo-im/GRIB2/tree/170-new-fire-parameters

**Comment by sebvi** [comment]
oups! it seems I accidently added the changes in the wrong branch then ... @amilan17 : Do you want me to move the changes in this branch and then delete it from the other branch to avoid issues?

**Comment by amilan17** [comment]
@sebvi yes, if you have the time.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT
