### ISSUE TITLE
New Table 4.2 entries proposed by Canada

### ISSUE THREAD

**Issue by efucile** [wmo-im/GRIB2#17]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-17

# Summary and purpose
This document proposes new GRIB2 Code Table 4.2 parameters. 

# Action proposed
The Team is requested to review the proposed new parameter and approve it for implementation within the May 2019 fast-track (FT2019-2) update to the WMO Manual on Codes. 

# Discussions
The tables annexed herewith contain proposed additions to Table 4.2 of the GRIB2 section of the Manual on Codes. These are necessary to reflect new post-processing diagnostics and Nowcasting forecasts being implemented at the Canadian Centre for Meteorological and Environmental Prediction. It is hoped that they are sufficiently general for eventual use by other Centers. 
We kindly request the IPET-CM to help us clarify whether the precipitation type probability parameters in Code Table 4.2, Product discipline 1 (hydrological products) may be used in the context of a general meteorology product. If not, we would be grateful for guidance on the proper procedure.   

# Detailed proposal
Proposed new entry for Code table 4.2

Parameter | Product Discipline | Parameter Category | Parameter number | Units
-- | -- | -- | -- | --
Thunderstorm intensity index | 0 | 7   (Thermodynamic stability) | 20 | Code   table 4.246 proposed new table
Precipitation intensity index | 0 | 1   (Moisture) | 122 | Code   table 4.247 proposed new table
Snow level | 0 | 19   (Physical atmospheric) | 40| m
Dominant precipitation type | 0 | 1   (Moisture) | 123 | Code   table 4.201 proposed modified table
Presence of showers | 0 | 1   (Moisture) | 124 | See Table 4.222
Presence of blowing snow | 0 | 1   (Moisture) | 125 | See Table 4.222
Presence of blizzard | 0 | 1   (Moisture) | 126 | See Table 4.222
Ice pellets (non water equivalent) precipitation rate | 0 | 1   (Moisture) | 127 | m/s

One table modification proposed:
GRIB2 - CODE TABLE 4.201, PRECIPITATION TYPE
Code Figure | Meaning
-- | --
0 | Reserved
1 | Rain
2 | Thunderstorm

New table Code table 4.246 - Thunderstorm intensity index

Title_en | SubTitle_en | CodeFlag | Value | MeaningParameterDescription_en | Note_en | UnitComments_en | Status
-- | -- | -- | -- | -- | -- | -- | --
Thunderstorm intensity |   | 0 |   | No thunderstorm occurence |   |   | Operational
Thunderstorm intensity |   | 1 |   | Weak thunderstorm |   |   | Operational
Thunderstorm intensity |   | 2 |   | Moderate thunderstorm |   |   | Operational
Thunderstorm intensity |   | 3 |   | Severe thunderstorm |   |   | Operational
Thunderstorm intensity |   | 4-254 |   | Reserved |   |   | Operational
Thunderstorm intensity |   | 255 |   | Missing |   |   | Operational

New table Code table 4.247 - Precipiation intensity index

Title_en | SubTitle_en | CodeFlag | Value | MeaningParameterDescription_en | Note_en | UnitComments_en | Status
-- | -- | -- | -- | -- | -- | -- | --
Precipitation intensity |   | 0 |   | No precipitation occurrence |   |   | Operational
Precipitation intensity |   | 1 |   | Light precipitation |   |   | Operational
Precipitation intensity |   | 2 |   | Moderate precipitation |   |   | Operational
Precipitation intensity |   | 3 |   | Heavy precipitation |   |   | Operational
Precipitation intensity |   | 4-254 |   | Reserved |   |   | Operational
Precipitation intensity |   | 255 |   | Missing |   |   | Operational

Reference doc file: https://wmoomm.sharepoint.com/:w:/s/wmocpdb/EdX0NSgC3AZCiJYksEB1PkgBr8HPRRefpw2vnjqLWaldkA?e=CKlXm4 

Reference meeting page: https://community.wmo.int/activity-areas/wmo-codes/meetings/ipet-cm-iii

**Comment by efucile** [comment]
I think that it would be better to have a new table also for the parameters in Numeric**** units. We should avoid putting information in the notes. Let's remember that notes are not in the xml or csv format of the tables which is used in by the decoders and are only in the pdf version of the manual.

**Comment by sebvi** [comment]
I am not in favor of using and expanding Code Table Discipline 1, Category 1 . My understanding is that parameters containing "probability of ..." are deprecated in favor of using the Template 4.5,setting type of generating process to "probability forecast", setting the probability type using Code Table 4.9, and then your limits for the probability in the following octets. 
This is why I don't think the parameters in discipline 1, category 1 should not be  accepted/added, they can already be encoded using the mechanism described above. (Note as well that 2 of your parameters have an entry in the reserved area for local code of the table).

What is the difference between your snow level and discipline 0, category 1, number 11?

For the "presence of ..." parameters, I would change the units to "boolean". What these fields provide is in fact a bitmap.

**Comment by sebvi** [comment]
I should also add that in GRIB3, discipline 1, category has been considered deprecated and has been deleted. I am in the process of committing the tables in the GRIB3 repository.

**Comment by tomkralidis** [comment]
cc @jbathegit 

Thanks @sebvi .  I have updated the proposal above by removing probability parameters in lieu of implementing with PDT 4.5, and updated the units of the presence parameters as booleans (per 4.222).

Note also I've changed snow level to parameter number from 36->40 given #25.  See the [following paper](https://ams.confex.com/ams/pdfpapers/140825.pdf) as reference/example of the term "Snow level".  We could also name this parameter "Snow level (melting level)" to reduce ambiguity if desired.

**Comment by chenxiaoxia2019** [comment]
@tomkralidis @ypell I have created a branch for this issue, with changes implemented in the table mentioned above. Could you please check it? Thanks.

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019; in comparing https://github.com/wmo-im/GRIB2/compare/issue-17 to the proposal above, is there any update on the below?

Parameter | Product Discipline | Parameter Category | Parameter number | Units
-- | -- | -- | -- | --
Thunderstorm intensity index | 0 | 7   (Thermodynamic stability) | 20 | Code   table 4.246 proposed new table
Snow level | 0 | 19   (Physical atmospheric) | 40| m

**Comment by chenxiaoxia2019** [comment]
@tomkralidis Hi, Tom. Thanks for your check. The above mentioned parameters have been updated in GRIB2_CodeFlag_4_2_CodeTable_en.csv. Please check it.

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019 .  I see tables 4.246 and 2.247 are non-existent. I updated the proposal above.  Can you update the branch with 4.246 and 4.247?

**Comment by chenxiaoxia2019** [comment]
@tomkralidis Hi, Tom, I updated the branch with tables 4.246 and 4.247. Could you please check it? Thanks.

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019 .  Looks good to me.  +1.

**Comment by amilan17** [comment]
SUMMARY: Add entries to Code Table 4.2, add Code Tables 4.246 and 4.247

**Comment by amilan17** [comment]
Approved by FT-2020-2.
