### ISSUE TITLE
New Fire parameters in Code Table 4.2, discipline 2, category 4 Fire weather products

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#170]
### Initial request

ECMWF is requesting additional entries in Code Table 4.2 discipline 2, category 4 Fire weather product to complement the existing list of available parameters.

### Amendment details

*ADD* in Code Table 4.2, discipline 2, category 4
| Code |Variable|Description|Units|
|--|--|--|--|
| ~~20~~ | ~~Burned Fraction~~ | ~~The  proportion of a grid box burned by a fire~~ | ~~fraction [0-1]~~ |
| ~~21~~ 20 |Burning area | The proportion of a grid box with an active fire| % |
| ~~22~~ 21 |Burnable area  | The proportion of a grid box which could potentially burn| % |
| ~~23~~ 22 |Un-burnable area | The proportion of a grid box which can't burn | % |
| ~~24~~ 23 |Fuel load|Total biomass of combustable material |kg m**2|
| ~~25~~ 24 |Combustion Completeness | combustion completeness= fraction of fuel load combusted during a fire | % |
| ~~26~~ 25 |Fuel moisture content | kg of water /kg of biomass | kg kg**-1 |

### Requestor(s)

Francesca Di Giuseppe, Sebastien Villaume (ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 2, category 4 (new entries)

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-5.10.2022 meeting notes: 
- change units to percentage; use existing code (3) instead of 20
- first @sebvi will ask researcher to confirm that it's the same parameter AND if they could be labeled with a specific model and/or could they use other existing parameters
-

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes:

still in progress

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes:
(@sebvi) the researcher said that these parameters are generic and common and are not specific to a particular model

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@sebvi will push branch asap and update issue summary units with "proportion"

**Comment by amilan17** [comment]
@jbathegit I updated the branch for @sebvi

**Comment by jbathegit** [comment]
I looked at the branch and the updates to CT 4.2 look fine.

However, I noted that there was also a change to template 4.91 included in the branch - did you mean to include that as well?

**Comment by amilan17** [comment]
@jbathegit good catch, that change is actually related to issue #166, technically it should be in a separate branch, but it's so minor, I don't think it will be fine as is.

**Comment by sebvi** [comment]
@jbathegit sorry it was a mistake on my side. As @amilan17  pointed it out the changes for 4.91 is meant to satisfy the decision in #166

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes:

@amilan17 and @marijanacrepulja  check consistency
