### ISSUE TITLE
New section 4 templates to encode optical products at a particular wavelength or for a particular wavelength range

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#171]
### Initial request

There has been considerable interest in ECMWF's true colour imagery of the IFS ([see AMETSOC paper](https://journals.ametsoc.org/view/journals/bams/101/7/bamsD190254.xml)) but it requires offline processing of model fields to generate reflectance fields in the Red (600-700nm), Green(500-600nm) and Blue(400-500nm) parts of the spectrum (coded in RGB).  ECMWF expect to be using a new version of the radiation scheme with bands coinciding with these three parts of the spectrum. We are also collaborating with the University of Massachusetts to obtain a new MODIS land-surface albedo climatology with 7 channels including these three bands in the visible.  Therefore it will be possible to compute RGB imagery of the Earth online as three grib fields, which can be used immediately for visualisation with minimal post processing.

We would like to produce the following accumulated fluxes (J/m2) for these parts of the spectrum:

1. Incoming top shortwave radiation
2. Net top shortwave radiation
3. Net surface shortwave radiation
4. Downwelling surface shortwave radiation
5. Direct part of the downwelling surface shortwave radiation
6. Net top shortwave radiation for clear skies
7. Net surface shortwave radiation for clear skies
8. Downwelling surface shortwave radiation for clear skies
9. Direct part of the downwelling surface shortwave radiation for clear skies

We are also planning to produce the following parameters for other specific part of the spectrum:

1. Photosynthetically active radiation at surface (total 400-700nm)
2.  Photosynthetically active radiation at surface for clear skies (total 400-700nm)
3. UV spectral flux by band of 5mn between 200 and 440nm 

The Copernicus Marine Service is interested in getting hold of surface downwelling shortwave in 12 bands between 400 and 700 nm at 25 nm intervals.  

### Amendment details

**ADD** the following templates entries in code table 4.0

| Code   | Description  |
| --- | --- |
| 108 | Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for generic optical products |
| 109 | Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for generic optical products |
| 110 | Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for generic optical products |
| 111 | Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval for generic optical products|

ADD template 4.108 - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for generic optical products

| **Octet** | **Content** |
| --- | --- |
| 10 | Parameter category |
| 11 | Parameter number |
| 12 | Type of interval (for wavelength)( code table 4.91) |
| 13 | Scale factor of first wavelength |
| 14-17 | Scaled value of first wavelength |
| 18 | Scale factor of second wavelength |
| 19-22 | Scaled value of second wavelength |
| 23 | Type of generating process |
| 24 | Background generating process identifier (defined by originating centre) |
| 25 | Forecast generating process identifier (defined by originating centre) |
| 26-27 | Hours after reference time of data cut-off |
| 28 | Minutes after reference time of data cut-off |
| 29 | Indicator of unit of time range |
| 30-33 | Forecast time in units defined by octet 29 |
| 34 | Type of first fixed surface |
| 35 | Scale factor of first fixed surface |
| 36-39 | Scaled value of first fixed surface |
| 40 | Type of second fixed surface |
| 41 | Scale factor of second fixed surface |
| 42-45 | Scaled value of second fixed surface |

ADD template 4.109 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for generic optical products

| **Octet** | **Content** |
| --- | --- |
| 10 | Parameter category |
| 11 | Parameter number |
| 12 | Type interval (for wavelength) (code Table 4.91) |
| 13 | Scale factor of first wavelength |
| 14-17 | Scaled value of first wavelength |
| 18 | Scale factor of second wavelength |
| 19-22 | Scaled value of second wavelength |
| 23 | Type of generating process |
| 24 | Background generating process identifier (defined by originating centre) |
| 25 | Forecast generating process identifier (defined by originating centre) |
| 26-27 | Hours after reference time of data cut-off |
| 28 | Minutes after reference time of data cut-off |
| 29 | Indicator of unit of time range |
| 30-33 | Forecast time in units defined by octet 29 |
| 34 | Type of first fixed surface |
| 35 | Scale factor of first fixed surface |
| 36-39 | Scaled value of first fixed surface |
| 40 | Type of second fixed surface |
| 41 | Scale factor of second fixed surface |
| 42-45 | Scaled value of second fixed surface |
| 46 | Type of ensemble forecast |
| 47 | Perturbation number |
| 48 | Number of forecasts in ensemble |

ADD template 4.110 - Average, accumulation, extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for generic optical products

|**Octet** | **Content** |
| --- | --- |
| 10 | Parameter category |
| 11 | Parameter number |
| 12 | Type of interval (for wavelength) (code Table 4.91) |
| 13 | Scale factor of first wavelength |
| 14-17 | Scaled value of first wavelength |
| 18 | Scale factor of second wavelength |
| 19-22 | Scaled value of second wavelength |
| 23 | Type of generating process |
| 24 | Background generating process identifier (defined by originating centre) |
| 25 | Forecast generating process identifier (defined by originating centre) |
| 26-27 | Hours after reference time of data cut-off |
| 28 | Minutes after reference time of data cut-off |
| 29 | Indicator of unit of time range |
| 30-33 | Forecast time in units defined by octet 29 |
| 34 | Type of first fixed surface |
| 35 | Scale factor of first fixed surface |
| 36-39 | Scaled value of first fixed surface |
| 40 | Type of second fixed surface |
| 41 | Scale factor of second fixed surface |
| 42-45 | Scaled value of second fixed surface |
| 46-47 | Year of end of overall time interval |
| 48 | Month of end of overall time interval |
| 49 | Day of end of overall time interval |
| 50 | Hour of end of overall time interval |
| 51 | Minute of end of overall time interval |
| 52 | Second of end of overall time interval |
| 53 | n - number of time range specifications describing the time intervals used to calculate the statistically processed field  |
| 54-57 | Total number of data values missing in statistical process |
| | 58-69 Specification of the outermost (or only) time range over which statistical processing is done |
| 58 | Statistical process used to calculate the processed field from the field at each time increment during the time range |
| 59 | Type of time increment between successive fields used in the statistical processing |
| 60 | Indicator of unit of time for time range over which statistical processing is done |
| 61-64 | Length of the time range over which statistical processing is done, in units defined by the previous octet |
| 65 | Indicator of unit of time for the increment between the successive fields used |
| 66-69 | Time increment between successive fields, in units defined by the previous octet |
|  | 70-nn  These octets are included only if n \> 1, where nn = 57 + 12 x n |
| 70-71 | As octets 58 to 69, next innermost step of processing |
| 72-nn | Additional time range specifications, included in accordance with the value of n. Contents as octets 58 to 69, repeated as necessary |

ADD template 4.111 - Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval for generic optical products

| **Octet** | **Content** |
| --- | --- |
| 10 | Parameter category |
| 11 | Parameter number |
| 12 | Type of interval (for wavelength) (code Table 4.91) |
| 13 | Scale factor of first wavelength |
| 14-17 | Scaled value of first wavelength |
| 18 | Scale factor of second wavelength |
| 19-22 | Scaled value of second wavelength |
| 23 | Type of generating process |
| 24 | Background generating process identifier (defined by originating centre) |
| 25 | Forecast generating process identifier (defined by originating centre) |
| 26-27 | Hours after reference time of data cut-off |
| 28 | Minutes after reference time of data cut-off |
| 29 | Indicator of unit of time range |
| 30-33 | Forecast time in units defined by octet 29 |
| 34 | Type of first fixed surface |
| 35 | Scale factor of first fixed surface |
| 36-39 | Scaled value of first fixed surface |
| 40 | Type of second fixed surface |
| 41 | Scale factor of second fixed surface |
| 42-45 | Scaled value of second fixed surface |
| 46 | Type of ensemble forecast |
| 47 | Perturbation number |
| 48 | Number of forecasts in ensemble |
| 49-50 | Year of end of overall time interval |
| 51 | Month of end of overall time interval |
| 52 | Day of end of overall time interval |
| 53 | Hour of end of overall time interval |
| 54 | Minute of end of overall time interval |
| 55 | Second of end of overall time interval |
| 56 | n - number of time range specifications describing the time intervals used to calculate the statistically processed field|
| 57-60 | Total number of data values missing in statistical process |
| | 61-72 Specification of the outermost (or only) time range over which statistical processing is done |
| 61 | Statistical process used to calculate the processed field from the field at each time increment during the time range |
| 62 | Type of time increment between successive fields used in the statistical processing |
| 63 | Indicator of unit of time for time range over which statistical processing is done |
| 64-67 | Length of the time range over which statistical processing is done, in units defined by the previous octet |
| 68 | Indicator of unit of time for the increment between the successive fields used |
| 69-72 | Time increment between successive fields, in units defined by the previous octet |
| | 73-nn These octets are included only if n \> 1, where nn = 60 + 12 x n |
| 73-74 | As octets 61 to 72, next innermost step of processing |
| 75-nn | Additional time range specifications, included in accordance with the value of n. Contents as octets 61 to 72, repeated as necessary |

### Requestor(s)

Sebastien Villaume (ECMWF representative) 

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.0 (new entries)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB templates 4.108 (new template)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB templates 4.109 (new template)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB templates 4.110 (new template)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB templates 4.111 (new template)

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-5.10.2022 meeting notes
- 4.108, octet 12: change to "type of interval (for wavelength)"
- validation will require deep review and samples

**Comment by sebvi** [comment]
Here is a link to the experimental version of ecCodes able to encode/decode the new templates:[ eccodes](https://confluence.ecmwf.int/display/ECC/Development+Snapshots)

Let me know if you do not have access.

**Comment by sebvi** [comment]
Here is a link to the experimental version of ecCodes able to encode/decode the new templates:[ eccodes](https://confluence.ecmwf.int/display/ECC/Development+Snapshots)

Let me know if you do not have access.
[imagery.zip](https://github.com/wmo-im/GRIB2/files/9900006/imagery.zip)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes:

@sebvi ready for validation; note, the template numbers that lennart is proposing are the same.

**Comment by sebvi** [comment]
Response to @SibylleK  and DWD

- what is the difference to the existing “optical properties of aerosol”-templates 4.48, 4.49, 4.80, 4.81?
 Wouldn’t it be possible to simply set the additional entries in e.g. 4.48 to missing to meet the requirements of the generic optical products?


The templates 4.48, 4.49, 4.80, 4.81 are specific for aerosol optical properties. The proposed templates 4.108 – 4.111 are intended to be used for satellite related parameters.
In template 4.48, 6 keys would have to be set to missing to encode the desired information (Aerosol type, Type of interval for first and second size, Scale factor of first size, Scaled value of first size in metres, Scale factor of second size, Scaled value of second size in metres), containing 13 bytes (12-24). As the names of the templates are related to aerosol optical properties and several keys should be set to missing, it is probably better to have separate templates to avoid confusion.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes:

ready for final review
