### ISSUE TITLE
New Parameter entries in Code table 4.2 for Copernicus and Destination Earth projects.

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#172]
### Initial request

[to be added]

### Amendment details

ADD in Code Table 4.2, in the correct disciplines and categories:

discipline 0, category 1
| Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Column   integrated divergence of total water mass flux | 0 | 1 | 165 | kg   m-2 s-1|
|Column   integrated water vapour flux | 0 | 1 | 166 | kg   m-1 s-1|
|Total   column supercooled liquid water | 0 | 1 | 167 | kg   m-2|

discipline 0, category 2
| Parameter | Product Discipline | Parameter Category | proposed Parameter number | Units |
| -- | -- | -- | -- | -- |
| Natural   logarithm of surface roughness length for heat | 0 | 2 | 54 | Numeric |
| Natural   logarithm of surface roughness length for moisture | 0 | 2 | 55 | Numeric |
| u-component   of neutral wind | 0 | 2 | 56 | m s-1 |
| v-component   of neutral wind | 0 | 2 | 57 | m s-1 |
| Magnitude   of turbulent surface stress | 0 | 2 | 58 | N m-2 |

discipline 0, category 3
| Parameter | Product Discipline | Parameter Category | proposed Parameter number | Units |
| -- | -- | -- | -- | -- |
|Standard   deviation of filtered subgrid orography | 0 | 3 | 38 | m|
|Column   integrated mass of atmosphere | 0 | 3 | 39 | kg   m-2|
|Column   integrated eastward geopotential flux | 0 | 3 | 40 | W   m-1|
|Column   integrated northward geopotential flux | 0 | 3 | 41 | W   m-1|
|Column   integrated divergence of water geopotential flux | 0 | 3 | 42 | W   m-2|
|Column   integrated divergence of geopotential flux | 0 | 3 | 43 | W   m-2|
|Height   of zero-degree wet-bulb temperature | 0 | 3 | 44 | m|
|Height   of one-degree wet-bulb temperature | 0 | 3 | 45 | m|

discipline 0, category 4
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|UV   visible albedo for diffuse radiation | 0 | 4 | 55 | %|
|UV   visible albedo for direct radiation | 0 | 4 | 56 | %|
|UV   visible albedo for direct radiation, geometric component | 0 | 4 | 57 | %|
|UV   visible albedo for direct radiation, isotropic component | 0 | 4 | 58 | %|
|UV   visible albedo for direct radiation, volumetric component | 0 | 4 | 59 | %|
|Photosynthetically   active radiation flux, clear sky | 0 | 4 | 60 | W   m-2|
|Direct short-wave radiation flux, clear sky | 0 | 4 | 61 | W   m-2|

discipline 0, category 5
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Near   IR albedo for diffuse radiation | 0 | 5 | 9 | %|
|Near   IR albedo for direct radiation | 0 | 5 | 10 | %|
|Near   IR albedo for direct radiation, geometric component | 0 | 5 | 11 | %|
|Near   IR albedo for direct radiation, isotropic component | 0 | 5 | 12 | %|
|Near   IR albedo for direct radiation, volumetric component | 0 | 5 | 13 | %|

discpline 0, category 6
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Sunshine  duration fraction (see Note) | 0 | 6 | 51 | Proportion|

Note: This parameter is the amount of sunshine in seconds over a given length of time in seconds. Sunshine is defined as a radiation intensity above 120 W m-2 

discipline 0, category 19
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Duct base height (see Note 1) | 0 | 19 | 41 | m|
|Trapping layer base height (see Note 1)| 0 | 19 | 42 | m|
|Trapping layer top height (see Note 1)| 0 | 19 | 43 | m|
|Mean vertical gradient of refractivity inside trapping layer (see Note 1) | 0 | 19 | 44 | m-1|
|Minimum vertical gradient of refractivity inside trapping layer (see Note 1) | 0 | 19 | 45 | m-1|

Note 1: A duct layer is an atmospheric layer with a refractivity which leads to a trapping of electromagnetic waves.  In a trapping layer the refractivity leads to a bending of EM waves, which is stronger than the earth’s curvature. 

discipline 0, category 21
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Column   integrated eastward heat flux | 0 | 21 | 19 | W   m-1|
|Column   integrated northward heat flux | 0 | 21 | 20 | W   m-1|
|Column   integrated potential+internal+latent energy | 0 | 21 | 21 | J   m-2|

discipline 2, category 0
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Skin   reservoir content | 2 | 0 | 50 | kg   m-2|
|Surface   runoff rate | 2 | 0 | 51 | kg   m-2 s-1|
|Sub-surface   runoff rate | 2 | 0 | 52 | kg   m-2 s-1|
|Low   vegetation cover | 2 | 0 | 53 | Proportion|
|High   vegetation cover | 2 | 0 | 54 | Proportion|
|Leaf   area index, low vegetation | 2 | 0 | 55 | m2   m-2|
|Leaf   area index, high vegetation | 2 | 0 | 56 | m2   m-2|
|Type   of low vegetation | 2 | 0 | 57 | Code   table 4.234|
|Type   of high vegetation | 2 | 0 | 58 | Code   table 4.234|
|Net   ecosystem exchange flux    (see Note 1) | 2 | 0 | 59 | kg   m-2 s-1|
|Gross   primary production flux   (see Note 1) | 2 | 0 | 60 | kg   m-2 s-1|
|Ecosystem   respiration flux   (see Note 1) | 2 | 0 | 61 | kg   m-2 s-1|

Note 1: This parameter can be used with templates for chemical constituents to specify a chemical species if needed, for instance: Net ecosystem CO2 exchange flux or Net ecosystem CH4 exchange flux 

discipline 3, category 1
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Reflectance   in 0.4 micron channel | 3 | 1 | 30 | %|

discipline 10, category 0
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|~~Mean wave period based on first moment~~ | ~~10~~ | ~~0~~ | ~~74~~ | ~~s~~ |
|~~Mean wave period based on first moment for swell~~ | ~~10~~ | ~~0~~ | ~~75~~ | ~~s~~ |
|~~Mean wave period based on first moment for wind waves~~ | ~~10~~ | ~~0~~ | ~~76~~ | ~~s~~ |
|~~Mean wave period based on second moment for swell~~ | ~~10~~ | ~~0~~ | ~~77~~ | s~~ |
|~~Mean wave period based on second moment for wind waves~~ | ~~10~~ | ~~0~~ | ~~78~~ | ~~s~~ |
|Mean direction of total swell | 10 | 0 | ~~79~~ 74 | degrees|
|Mean direction of wind waves | 10 | 0 | ~~80~~ 75 | degrees|
|Charnock (see Note 1)| 10 | 0 | ~~81~~ 76 | Numeric|
|Wave   Spectral Skewness | 10 | 0 | ~~82~~ 77 | Numeric|
|Wave   energy flux magnitude | 10 | 0 | ~~83~~ 78 | W   m-1|
|Wave   energy flux mean direction | 10 | 0 | ~~84~~ 79 | Degree   true|
|Ratio   of wave angular and frequency width | 10 | 0 | ~~85~~ 80 | Numeric|
|Free   convective velocity over the oceans | 10 | 0 | ~~86~~ 81 | m   s-1|
|Air   density over the oceans | 10 | 0 | ~~87~~ 82 | kg   m-3|
|Normalized   energy flux into waves (see Note 2) | 10 | 0 | ~~88~~ 83 | Numeric|
|Normalized   stress into ocean (see Note 2)| 10 | 0 | ~~89~~ 84 | Numeric|
|Normalized   energy flux into ocean (see Note 2) | 10 | 0 | ~~90~~ 85 | Numeric|
|Surface elevation   variance due to waves (over all frequencies and directions) | 10 | 0 | ~~91~~ 86 | m2 s rad-1|

Note 1: The Charnock  parameter accounts for increased aerodynamic roughness as wave heights grow due to increasing surface stress. It depends on the wind speed, wave age and other aspects of the sea state and is used to calculate how much the waves slow down the wind.
Note 2: Parameters are normalised by being divided by the product of air density and the square of the friction velocity.

discipline 10, cateogry 3
|Parameter | Product   Discipline | Parameter   Category | proposed   Parameter number | Units|
|-- | -- | -- | -- | --|
|Deviation of   sea level from mean with inverse barometer correction | 10 | 3 | 20 | m|

### Requestor(s)

Matthew Griffith, Robert Osinski and Sebastien Villaume (all ECMWF)

### Stakeholder(s)

ECMWF
Copernicus program
Destination Earth program

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-1-and-2.11.2022) notes:

@SibylleK provided comments. Add notes for sunshine duration fraction, duct base and trapping layer. Add hypen to high/low vegetation. Rephrase 'Charnock' to something more meaningful. Add note for normalized \* (normalized by what?). Clarify meaning of 'over the oceans' or is it needed?

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes:
(@sebvi) reviewing comments and will update issue

**Comment by sebvi** [comment]
!!! REMOVED. the following parameters from the proposal: !!!
Mean wave period based on first moment			10	0	74	s
Mean wave period based on first moment for swell	10	0	75	s
Mean wave period based on first moment for wind waves	10	0	76	s
Mean wave period based on second moment for swell	10	0	77	s
Mean wave period based on second moment for wind waves	10	0	78	s

"Mean wave period based on first moment"  is already defined as "inverse mean wave frequency"
"Mean wave period based on second moment" is already defined as  "mean zero-crossing period"
These are alternative naming definitions that make sense if you are dealing with waves according to our in-house expert so the parameters we were proposing are already defined in 

Inverse mean wave frequency				10	0	25	s
Inverse mean frequency of wind waves			10	0	26	s
Inverse mean frequency of total swell			10	0	27	s
Mean zero-crossing period of wind waves			10	0	29	s
Mean zero-crossing period of total swell		10	0	30	s

**Comment by sebvi** [comment]
Response to comments formulated by @SibylleK  and DWD:

- Maybe a more “orthogonal” and flexible alternative to entries:
“Height of zero-degree wet-bulb temperature  0  3  44  m”
“Height of one-degree wet-bulb temperature   0  3  45  m”

could be already existing:

“Geometric height                                             0  3  6    m”
and a new entry in Code Table 4.5 – Fixed surface types and units:
“Level of specified web-bulb temperature                       K (or °C instead?)”

After discussing with our expert, it does not seem that we will ever produce this with other values of wet bulb temperature so it feels a bit overkill to create a new type of Fixed surface for this purpose. Instead of 2 parameters in code tables, we would have 1 parameter in it and 1 entry in Code table 4.5 .

-Regarding New entry:
“Sunshine duration fraction                               0  6  51  Proportion”
The following entries do already exist:
“Sunshine                                                          0  6  24  Numeric”
“Sunshine duration                                            0  6  33  s”

Maybe one could add a Note for the new entry to explain: “fraction” of what?
For instance: “Note xyz: Sunshine duration fraction of local length of day(?)“.

This sunshine concept is tricky. Strictly speaking the sunshine duration parameter in seconds is the amount of seconds over a period of time when the radiation intensity is above 120 W/m2 . My understanding is that 0/6/24 is the instantaneous radiation: at a given time t, if the downward radiation is above 120 W/m-2 then the parameter is 1 otherwise it is 0. Then if you accumulate this over a period a time, and your delta t is 1 seconds, it is the number of seconds in the time interval where radiation is over or equal to 120 W/m-2. Strictly speaking 0/6/33 could be encoded as 0/6/24 + accum key and should then be deprecated. Now our new parameter is different, it is a fraction so in a sense it is the accumulation in seconds I just described divided by the overall size of the accumulation window in seconds. For instance 2468 seconds of sunshine during the last hour is 2468/3600 = 0.6855555 . Does it makes sense? 

- New entries in discipline 0, category 19: What do “Duct” and “Trapping layer” mean? Maybe add a Note for non-experts?

A duct layer is an atmospheric layer with a refractivity which leads to a trapping of electromagnetic waves. In a trapping layer the refractivity leads to a bending of EM waves, which is stronger than the earth’s curvature.

- How does the new entry:
“Surface runoff rate                                             2  0  51  kg m-2 s-1”
compare with the existing entry:
“Water runoff and drainage rate                          2  0  42  kg m-2 s-1”?

"Water runoff and drainage rate” includes the drainage rate while “surface runoff rate” does not.


- The description of the following new entry:
“Charnock                                                           10  0  81  Numeric”
could be a bit more detailed. Maybe “Charnock xyz parameter/coefficient”?

Not sure I understand the comment. Charnock is roughness over water, what else should be specify?

- The new entries containing “… over the oceans”: What does that mean? Does it refer to an air layer directly above the water surface, which has to be specified by first and second fixed surfaces?

Parameters containing "over the oceans" are only calculated over water bodies represented in the ocean wave model. It is interpolated from the atmospheric model horizontal grid onto the horizontal grid used by the ocean wave model.

- The new entries containing “Normalized …”: Should there be a Note to clarify the question: “Normalized” by what?

Parameters are normalised by being divided by the product of air density and the square of the friction velocity.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes:

sebastien posted answers to questions (in comment above), updated the proproposal to indicate changes. @sebvi will add notes to the issue summary and add note for Charnock. @SibylleK will review the feedback and updated proposal.

**Comment by sebvi** [comment]
branch updated with new wave parameter numbering, added a parameter that was missing (last one of the list) and added all the notes we discussed
