### ISSUE TITLE
New templates for spatio-temporal changing tiles

### ISSUE THREAD

**Issue by efucile** [wmo-im/GRIB2#18]
# Summary and purpose
Additional template definitions for statistically processed values to complete the set of templates for spatio-temporal changing tiles 

# Action proposed
The team is requested to review the proposed new templates and approve it for implementation within the May 2019 fast-track (FT2019-2) update to the WMO Manual on Codes. 

# Discussions
The coding of spatio-temporal tiles at a point in time for deterministic forecasts (Product definition template number 55) and for individual ensemble forecast (Product definition template number 59) is already defined and used by the German weather service DWD. The definitions including a statistical process are missing. To complete the set of tile templates “average, accumulation and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval” for deterministic and ensemble forecast of spatio-temporal changing tiles have to be defined. 

The coding of spatio-temporal tiles at a point in time for deterministic forecasts (Product definition template 4.55) and for individual ensemble forecast (Product definition template 4.59) is already defined and used by Deutscher Wetterdienst (DWD), however, the definitions including a statistical process are missing.  Ms Sibylle Krebber, DWD, proposed new product definition templates for deterministic and ensemble forecast of spatio-temporal changing tiles in order to complete the set of tile templates.  The proposed templates composed of the existing PDT 4.55 and 4.59 and statistical process definitions.

The meeting agreed the proposal for FT2019-2 (Cat. 1d) as in the Annex to this paragraph, provided the validation will be finished by the end of June 2019.  NCEP will assist the validation.

# Detailed proposal
Please add 2 new entries in 

Code table 4.0 – Product definition template number 

Code figureMeaning 

62Average, accumulation and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time 

63Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles 

 

Please add 2 new templates: 

 

Product definition template 4.62 – average, accumulation and/or extreme values or other statistically processed values at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles at a horizontal level or horizontal layer at a point in time  

Octet No. Contents  

10 Parameter category (see Code table 4.1)  

11 Parameter number (see Code table 4.2)  

12 Tile classification (see Code table 4.242)  

13 Total number (NT) of tile/attribute pairs (see Notes 1 and 2) 

14 Number of used spatial tiles (NUT) (see Notes 1 and 2)  

15 Tile index (ITN = {1,…, NUT}) (see Note 1)  

16 Number of used tile attributes (NAT) for tile ITN (see Note 1)  

17 Attribute of tile (see Code table 4.241)) (A = {A(1),…, A(NAT(ITN))}) (see Note 1)  

18 Type of generating process (see Code table 4.3)  

19 Background generating process identifier (defined by originating centre)  

20 Analysis or forecast generating process identifier (defined by originating centre)  

21–22 Hours of observational data cut-off after reference time (see Note 3)  

23 Minutes of observational data cut-off after reference time  

24Indicator of unit of time range (see Code table 4.4)  

25–28 Forecast time in units defined by octet 24 (see Note 4) 

29 Type of first fixed surface (see Code table 4.5)  

30 Scale factor of first fixed surface  

31–34 Scaled value of first fixed surface  

35 Type of second fixed surface (see Code table 4.5)  

36 Scale factor of second fixed surface  

37–40 Scaled value of second fixed surface 

Shape41-42 Year  

43 Month  

44 Day Time of end of overall time interval  

45 Hour  

46 Minute  

47 Second  

48 n – number of time range specifications describing the time intervals used to calculate the statistically processed field  

49–52 Total number of data values missing in statistical process  

53-64 Specification of the outermost (or only) time range over which statistical processing is done  

53 Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code table 4.10)  

54 Type of time increment between successive fields used in the statistical processing (see Code table 4.11)  

55 Indicator of unit of time for time range over which statistical processing is done (see Code table 4.4)  

56–59 Length of the time range over which statistical processing is done, in units defined by the previous octet  

60 Indicator of unit of time for the increment between the successive fields used (see Code table 4.4)  

61-64 Time increment between successive fields, in units defined by the previous octet (see Notes 5 and 6)  

65-nn These octets are included only if n > 1, where nn = 52 + 12 x n  

65-76 As octets 53 to 64, next innermost step of processing  

77–nn Additional time range specifications, included in accordance with the value of n. Contents as octets 53 to 64, repeated as necessary 

 

Notes:  

(1) See Note 1 under product definition template 4.55.  

(2) For more information, see Part B, GRIB Attachment IV.  

(3) Hours greater than 65534 will be coded as 65534 

(4) The reference time in section 1 and the forecast time together define the beginning of the overall time interval.  

(5) An increment of zero means that the statistical processing is the result of a continuous (or near continuous) process, not the processing of a number of discrete samples. Examples of such continuous processes are the temperatures measured by analogue maximum and minimum thermometers or thermographs, and the rainfall measured by a rain gauge.  

(6) The reference and forecast times are successively set to their initial values plus or minus the increment, as defined by the type of time increment (one of octets 54, 66, 78, ...). For all but the innermost (last) time range, the next inner range is then processed using these reference and forecast times as the initial reference and forecast times. 

 

 

Product definition template 4.63 – Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for spatio-temporal changing tiles 

Octet No. Contents  

10 Parameter category (see Code table 4.1)  

11 Parameter number (see Code table 4.2)  

12 Tile classification (see Code table 4.242)  

13 Total number (NT) of tile/attribute pairs (see Notes 1 and 2) 

14 Number of used spatial tiles (NUT) (see Notes 1 and 2)  

15 Tile index (ITN = {1,…, NUT}) (see Note 1)  

16 Number of used tile attributes (NAT) for tile ITN (see Note 1)  

17 Attribute of tile (see Code table 4.241)) (A = {A(1),…, A(NAT(ITN))}) (see Note 1)  

18 Type of generating process (see Code table 4.3)  

19 Background generating process identifier (defined by originating centre)  

20 Analysis or forecast generating process identifier (defined by originating centre)  

21–22 Hours of observational data cut-off after reference time (see Note 3)  

23 Minutes of observational data cut-off after reference time  

24Indicator of unit of time range (see Code table 4.4)  

25–28 Forecast time in units defined by octet 24 (see Note 4) 

29 Type of first fixed surface (see Code table 4.5)  

30 Scale factor of first fixed surface  

31–34 Scaled value of first fixed surface  

35 Type of second fixed surface (see Code table 4.5)  

36 Scale factor of second fixed surface  

37–40 Scaled value of second fixed surface 

41Type of ensemble forecast (see Code table 4.6) 

42Perturbation number 

43Number of forecasts in ensemble 

Shape44-45 Year  

46 Month  

47 Day Time of end of overall time interval  

48 Hour  

49 Minute  

50 Second  

51 n – number of time range specifications describing the time intervals used to calculate the statistically processed field  

52-55 Total number of data values missing in statistical process  

56-67 Specification of the outermost (or only) time range over which statistical processing is done  

56 Statistical process used to calculate the processed field from the field at each time increment during the time range (see Code table 4.10)  

57 Type of time increment between successive fields used in the statistical processing (see Code table 4.11)  

58 Indicator of unit of time for time range over which statistical processing is done (see Code table 4.4)  

59–62 Length of the time range over which statistical processing is done, in units defined by the previous octet  

63Indicator of unit of time for the increment between the successive fields used (see Code table 4.4)  

64-67 Time increment between successive fields, in units defined by the previous octet (see Notes 5 and 6)  

68-nn These octets are included only if n > 1, where nn = 55 + 12 x n  

68-79 As octets 56 to 67, next innermost step of processing  

80–nn Additional time range specifications, included in accordance with the value of n. Contents as octets 56 to 67, repeated as necessary 

 

Notes:  

(1) See Note 1 under product definition template 4.55.  

(2) For more information, see Part B, GRIB Attachment IV.  

(3) Hours greater than 65534 will be coded as 65534 

(4) The reference time in section 1 and the forecast time together define the beginning of the overall time interval.  

(5) An increment of zero means that the statistical processing is the result of a continuous (or near continuous) process, not the processing of a number of discrete samples. Examples of such continuous processes are the temperatures measured by analogue maximum and minimum thermometers or thermographs, and the rainfall measured by a rain gauge.  

(6) The reference and forecast times are successively set to their initial values plus or minus the increment, as defined by the type of time increment (one of octets 57, 69, 81, ...). For all but the innermost (last) time range, the next inner range is then processed using these reference and forecast times as the initial reference and forecast times.

**Comment by SibylleK** [comment]
The templates 4.62 and 4.63 were validated in May 2019 and included in FT 2019-2.
(I sent the validation report 3rd of June)
They are operational since November 2019.
 They were published and included in version 24, but they are missing in version 25.

@efucile could you please check and include the missing templates?
Thank you very much!
Regards,
Sibylle

**Comment by efucile** [comment]
@SibylleK they are included in version 25, but they are not in the gitHub repository. I will add them.

**Comment by efucile** [comment]
Now the files are in version 24 and 25
