### ISSUE TITLE
Code Table 4.2 : new ocean wave parameters 

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#194]
### Initial request

In the context of the development of its wave model, ECMWF is requesting new ocean wave parameters which are variations of how the maximum individual wave (or crest) height is computed.

### Amendment details

ADD new entries to Code Table 4.2
| Name | discipline | category | number | units|
|--|--|--|--|--|
|Envelop maximum individual wave height|10| 0 | 93 | m | 
|Time domain maximum individual crest height |10| 0 | 94 | m |
|Time domain maximum individual wave height|10| 0 | 95 | m |
|Space time maximum individual crest height|10| 0 | 96 | m |
|Space time maximum individual wave height|10| 0 | 97 | m |

### Requestor(s)

Sebastien Villaume (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 10, category 0

### Expected impact of change

None

**Comment by chenxiaoxia2019** [comment]
25-April-meeting:
(1)Sebastian to add the relevant paper for reference to the GitHub; to approach the wave experts in ECMWF for definitions
(2)Jeff proposes to add notes to the new ocean wave parameters

**Comment by sebvi** [comment]
The detailed description of the parameters proposed can be found in the appendix section of the following publication:

Francesco Barbariol, Jean-Raymond Bidlot, Luigi Cavaleri, Mauro Sclavo, Jim Thomson, Alvise Benetazzo
maximum wave heights from global model reanalysis
Progress in Oceanography  (IF4.08),  Pub Date : 2019-07-01, DOI: 10.1016/j.pocean.2019.03.009

In particular, proposed parameters 94, 95, 96 and 97 are computed using the equations 2, 5, 10 and 11 respectively.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023) 

[@sebvi](https://github.com/sebvi) add samples and update branch;

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023) 

[@sebvi](https://github.com/sebvi) add samples and update branch;

**Comment by sebvi** [comment]
Btanch updated, we are preparing some samples.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

branch is ready
