### ISSUE TITLE
Code Table 4.2 : new fire parameters

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#195]
### Initial request

ECMWF is requesting new fire parameters for its global emergency fire forecasting service.

### Amendment details

ADD new entries in Code table 4.2, discipline 2, category 4
| Name | code | units | Comment/definition|
|--|--|--|--|
|live leaf fuel load|27| kgm-2| amount of biomass fro live leaves |
|live wood fuel load |28|kgm-2|amount of biomass from woody components|
|dead leaf fuel load|29 |kgm-2|amount of biomass from dead leaves|
|dead wood fuel load|30|kgm-2|amount of biomass from dead woody components|
|live fuel moisture content|31|kgkg-1|amount of water per amount of mass in live vegetation|
|fine dead leaf moisture content|32|kgkg-1|Amount of water per amount of mass in fine dead leaf fuel bed. These fuels include herbaceous plants and leaf litter. Fine dead leaf is classified as a 1-h fuel in the Nelson model as moisture responds on hourly timescales to atmospheric conditions. Typical diameter is 0.2 cm. Values range between 0.01 and 0.8.|
|dense dead leaf moisture content|33|kgkg-1|Amount of water per amount of mass in dense dead leaf fuel bed. These fuels include herbaceous plants and small sticks. Dense dead leaf is classified as a 10-h fuel in the Nelson model as moisture responds on sub-daily timescales to atmospheric conditions. Typical diameter is 0.6 cm. Values range between 0.01 and 0.6.|
|fine dead wood moisture content|34|kgkg-1|Amount of water per amount of mass in fine dead wood fuel bed. These fuels include large sticks and logs. Fine dead wood is classified as a 100-h fuel in the Nelson model as moisture responds on daily-to-weekly timescales to atmospheric conditions. Typical diameter is 2.0 cm. Values range between 0.01 and 0.5.|
|dense dead wood moisture content|35|kgkg-1|Amount of water per amount of mass in dense dead wood fuel bed. These fuels include fallen trees and large logs. Dense dead wood is classified as a 1000-h fuel in the Nelson model as moisture responds on monthly timescales to atmospheric conditions. Typical diameter is 6.0 cm. Values range between 0.01 and 0.4.|

### Requestor(s)

Sebastien Villaume (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 2, category 4

### Expected impact of change

None

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023) notes: 

[@sebvi](https://github.com/sebvi) update branch;

**Comment by sebvi** [comment]
branch updated

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

ready
