### ISSUE TITLE
Code Table 4.2, discipline 0, category 19: new entries for  persistent contrails

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/GRIB2#198]
### Initial request

DWD is requesting two new contrail parameters.

The existing entries in code table 4.2: 
Name | Product Discipline | Parameter Category | Parameter Number | Units
-- | -- | -- | -- | --
Contrail top | 0 | 19 | 15 | m
Contrail base | 0 | 19 | 16 | m

stand for top and base of condensation trails in general.
We request two new parameters for top and base of persistent contrails. 
Persistent contrails, which may persist for several hours (Cirrus homogenitus, Cirrus homomutatus, [1]) are of special interest, for instance, as they increase the general cloudiness of the atmosphere (see, e.g. [2]).
In addition, aviation is very interested in information on these clouds. 
Persistent contrails may be diagnosed using the method described in [3].
Currently, however, we do not have the possibility to distinguish explicitly between persistent and non-persistent contrails with respect to GRIB metadata, as the existing "contrail" parameters may be interpreted as including both types, persistent and non-persistent.

### Amendment details

Add new entires in code table 4.2 dicipline 0, category 19:
Name | Product Discipline | Parameter Category | proposed Parameter Number | Units
-- | -- | -- | -- | --
Top of persistent contrails | 0 | 19 | 48 | m
Base of persistent contrails | 0 | 19 | 49 | m

### Requestor(s)

Sebastian Borchert (DWD)
Sibylle Krebber (DWD)
Petra Baumann (MeteoSwiss)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 19

### Expected impact of change

MEDIUM

### References

[1] [WMO International Cloud Atlas](https://cloudatlas.wmo.int/en/home.html)
[2] [Fereral Aviation Administration (USA), Aircraft Contrails Factsheet](https://www.faa.gov/regulations_policies/policy_guidance/envir_policy/media/contrails.pdf)
[3] Appleman H. (1953) _The formation of exhausted condensation trails by jet aircraft_. Bulletin American Meteorological Society, Vol. 34, 14 – 20.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023/) notes: 

Team agrees to proposal

**Comment by amilan17** [comment]
@SibylleK Did you want this to go through FT2023-2? If so I created a branch for you to update.

**Comment by SibylleK** [comment]
Thank you very much @amilan17!  Yes, it should go through FT2023-2.
Branch is updated.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

ready
