### ISSUE TITLE
Code Table 1.3 : adding Destination Earth entries 

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#199]
### Initial request

A bit of a late request, ECMWF would like to propose 2 new entries in Code Table 1.3 to encode Destination Earth data.

The Destination Earth (DestinE) is a flagship initiative of the European Commission to develop a highly accurate digital model of the Earth on a global scale.This model will monitor, simulate and predict the interaction between natural phenomena and human activities. It will contribute to achieving the objectives of the twin transition, green and digital as part of the European Commission’s [Green Deal](https://ec.europa.eu/info/strategy/priorities-2019-2024/european-green-deal_en) and [Digital Strategy](https://ec.europa.eu/info/strategy/priorities-2019-2024/europe-fit-digital-age_en).

ECMWF will be responsible of the "digital twins" implementation while ESA and EUTMETSAT will be responsible for other parts of the initiative (service platform, data lakes, etc.)

Digital twins are digital replicas of the highly complex Earth systems, they are based on a seamless fusion of real-time observations and high-resolution predictive modelling in the thematic areas, starting from the extreme events and climate change adaptation.

The long-term goal is to integrate additional digital twins such as on oceans or biodiversity creating a comprehensive digital twin of the Earth. The digital twins of DestinE will provide users with tailored access to high-quality knowledge for user-specific scenario development that can support evidence-based decision-making.

### Amendment details

ADD in Code Table 1.3:

| Code | Meaning |
|--|--|
| 12 | Destination Earth (DestinE) |
| 13 | Destination Earth (DestinE) test |

### Requestor(s)

Sebastien Villaume, ECMWF

### Stakeholder(s)

European Commission
ECMWF
EUMETSAT
ESA

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 1.3

### Expected impact of change

MEDIUM

### References

[ Destination Earth website from European Commission](https://digital-strategy.ec.europa.eu/en/policies/destination-earth#tab_2)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023) notes: 

[@sebvi](https://github.com/sebvi) update branch; noting that Destination Earth (DestinE) test is needed;

**Comment by sebvi** [comment]
branch updated

**Comment by amilan17** [comment]
@sebvi branch looks good -- Do you still want (DestinE) as part of the name?

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

ready
