### ISSUE TITLE
New GRIB2 code Table 4.2 entries requested by Norway 

### ISSUE THREAD

**Issue by efucile** [wmo-im/GRIB2#20]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-20

# Summary and purpose
This document proposes new GRIB2 Code Table 4.2 parameters. 

# Action proposed
The Team is requested to review the proposed new parameter and approve it for implementation. 

# Discussions
The tables in this proposal contain parameters that will be of crucial importance for the Copernicus Arctic Regional Reanalysis project which will start its production very soon. These parameters have been widely used as GRIB1 parameters in the hirlam numerical weather prediction community, and we thus believe they will be of high relevance outside the aforementioned reanalysis project. 

Since the proposal has been submitted during the meeting and requires specific scientific expertise, the meeting decided to draft the amendment with a small group and then share it with other participants of the meeting.  Dr Sebastien Villaume, ECMWF, offered to support the drafting work.  The initial proposal is as in the Annex to this paragraph.

 Detailed proposal
Proposed new entry for Code Table 4.2: 

Parameter | Product Discipline | Parameter Category | Parameter number | Units
-- | -- | -- | -- | --
Total solid precipitation rate 1) | 0 | 1 | To be decided | kg m-2 s-1
Direct normal short-wave radiation flux 2) | 0 | 4 | “ | W m-2
Latent heat net flux due to evaporation 3) | 0 | 0 | “ | W m-2
Latent heat net flux due to sublimation 4) | 0 | 0 | “ | W m-2
Fog 5) | 0 | 6 | “ | %

Comments:  

1. Total solid precipitation includes the sum of all types of solid water, e.g. graupel, snow and hail 
2. Normal flux is on a surface lifted to be normal to sun rays 
3. Evaporation is the conversion of liquid into vapor 
4. Sublimation is the conversion of solid state into vapor 
5. Fog is defined as cloud cover in the lowest model level 

Reference document: https://wmoomm.sharepoint.com/:w:/s/wmocpdb/EXE60TyG2FtCjAmwP90CvsoBPzAHgvYwHSOfCQO_wetbuA?e=TcgDt9

Reference meeting page: https://community.wmo.int/activity-areas/wmo-codes/meetings/ipet-cm-iii

**Comment by sebvi** [comment]
This went under the radar, I should have reviewed these back in November. Since I had help drafting the initial proposal, the only remaining task was to assign a code for each of these new parameters.

Proposed new entry for Code Table 4.2: 

Parameter | Product Discipline | Parameter Category | Parameter number | Units
-- | -- | -- | -- | --
Total solid precipitation rate 1) | 0 | 1 | 122 | kg m-2 s-1
Direct normal short-wave radiation flux 2) | 0 | 4 | 54 | W m-2
Latent heat net flux due to evaporation 3) | 0 | 0 | 30 | W m-2
Latent heat net flux due to sublimation 4) | 0 | 0 | 31 | W m-2
Fog 5) | 0 | 6 | 50 | %

Regarding the associated comments, I think comments 3. and 4. can be dropped while comments 1., 2. and 5. should be added as notes in uuuuuuuuuuuuuuunder the relevant Code Tables respectively.

**Comment by sebvi** [comment]
Update total precipitation rate to be code 123 to not clah with issue #15

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien. I noticed that **total precipitation rate** with the parameter 123 has clashed with issue 20.

**Comment by sebvi** [comment]
yes @chenxiaoxia2019 you are right. I picked the number before it was done in issue #17 and I made sure it was not clashing with anything else at that time (for instance issue #15 , see my comment above on the 21 April.)
I think @tomkralidis updated his proposal on the 5th May (see his comment in issue #17 ) and he probably did not realized that 123 was already planned to be assigned in this issue. 
This sort of things happens all the time during consolidation of the various proposals.  I don't mind if the number is changed here or if we shift the entry 123 in #17 to become entry 128.

**Comment by chenxiaoxia2019** [comment]
@sebvi Thanks for your quick reply. I have already created the branch for issue #17, so I change the total precipitation rate from 123 to 128. Thanks for your understanding.

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien. I created a new branch for this issue. Could you please check it? Many thanks.

**Comment by sebvi** [comment]
@chenxiaoxia2019 The entries are correctly inserted in code Table 4.2. The branch seems ok to me. Thank you

**Comment by amilan17** [comment]
SUMMARY: Add entries to Code Table 4.2.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
