### ISSUE TITLE
Missing code table entry in 4.59, typo in template 4.78, 

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/GRIB2#200]
### Details

In template 4.59 the entry for codeTable is missing for "Attribute of tile". It should be 4.241.
(The code table is only included in the Content of  Octet 17 so far.)

There is a typo in GRIB template 4.78: the codeTable for "Atmospheric chemical constituent type" should be 4.230 instead of 4.23.

### Requestor

Sibylle Krebber (DWD), @SibylleK

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023/) notes: 

@amilan17 will update branch;

**Comment by SibylleK** [comment]
Thank you @amilan17 !
I checked and reviewed the PR.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

ready
