### ISSUE TITLE
Template 3.130 Irregular Latitude/longitude grid: deprecated or non-existent?

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#202]
### Initial request

While working on the new HEALPix grid that I initially planned to put in template 3.130, I realised that 130 was assigned in the past to a template for irregular lat/lon grids.
The templates is present in version 5 of the GRIB2 tables, maybe before but I don't know where to check, but was removed for the tables in version 8.

In order to make clear that 130 was used in the past and to prevent this happening again, I propose to reinstate this template and mark it as deprecated/never validated, like it was done for some other templates. 

### Amendment details

reinstate template 3.130 from version 8, mark it deprecated.

### Requestor(s)

Sebastien Villaume (ECMWF)
Shahram Najm (ECMWF)

### Stakeholder(s)

WMO
ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB template 3.130

### Expected impact of change

LOW

### References

older version of the tables: https://community.wmo.int/en/activity-areas/wis/previous-versions

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023](https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023) notes: 

team found a copy of the table in v6 that was in a validation state and apparently it was never validated.
