### ISSUE TITLE
new entry for "Convectively-induced turbulence" in Code Table 4.2

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/GRIB2#218]
### Initial request

The NCEP Environmental Modeling Center requests a new parameter in Category 19 of GRIB2 Code Table 4.2.

### Amendment details

New entry in Code table 4.2: 
Name | Discipline | Category | Parameter | Units
-- | -- | -- | -- | --
Convectively-induced turbulence (CIT) (eddy dissipation rate) | 0 | 19 | 50 | m2/3 s-1

### Requestor(s)

NCEP Environmental Modeling Center

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 19

### Expected impact of change

None

**Comment by jbathegit** [comment]
I realize this is probably too late for FT2023-2, and if that's the case then resetting the mileston to FT2024-1 is fine.

**Comment by sebvi** [comment]
Hi @jbathegit,

We have few turbulence and eddy dissipation parameters in Code Table 4.2 discipline 0 category 19 already: entries 28 to 32.
Could you explain how this new parameter relates to the existing ones? is it a new separate contribution to turbulence/eddy dissipation? is it a component of or a contribution to one of the existing parameters? I am not an expert in this, I just want to check

**Comment by jbathegit** [comment]
Hi @sebvi.  According to our experts, CIT (convectively-induced) is completely different from CAT (clear air) or MWT (mountain wave) turbulence.  In other words, they are 3 different types of turbulence.  Furthermore, the eddy dissipation parameter (defined in existing parameter 30) is a filtered product derived from the maximum of the CIT, CAT, and MWT.  So that's why they're requesting a completely new parameter in category 19.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023](https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023) notes:

the team agrees to the proposal;

**Comment by jbathegit** [comment]
> branch is updated and ready for validation

Yes, the branch is updated and ready to be merged.  Sorry I submitted an unnecessary PR for this!  

However, I think we agreed that no formal validation is required and that this is already fully approved for FT2024-1, correct?

**Comment by amilan17** [comment]
@jbathegit the only validation needed is editorial and consistency check.
