### ISSUE TITLE
Encoding of Drought indexes as defined by WMO 

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#221]
### Initial request

The WMO Handbook of Drought Indicators and Indices lists several indices which are not yet defined in the WMO GRIB2 table 4.2. This proposal suggests adding them together with additional entries in the tables 4.10, 4.101 and 4.102 to be used with the GRIB2 templates 4.105 to 4.107 and 4.112. These templates are designed to encode the reference period and processing of the data and we propose to extend these tables to be able to specify the underlying distribution used for the indices

### Amendment details

Add a new entry in Code Table 4.1: Parameter category by product discipline

|Code	|Name|
|--|--|
|22	|Drought indices|

Create a new category "drought indices" in Code Table 4.2 under discipline 0
Product discipline 0 - Meteorological products, parameter category 22: drought indices

|Parameter number|	Parameter name|	unit|
|--|--|--|
|0 |Standardised Precipitation Index (SPI)|	Numeric|
|1 |Standardised Precipitation Evapotranspiration Index (SPEI)|	Numeric|
|2 |Standardised Streamflow Index (SFI)|	Numeric|
|3 |Standardised Reservoir Supply Index (SRSI)|	Numeric|
|4 |Standardised Water-level Index (SWI)|	Numeric|
|5 |Standardised Snowmelt and Rain Index (SMRI)|	Numeric|
|6 |Streamflow Drought Index (SDI)|	Numeric|

A description of these indices is available in the WMO Handbook of Drought Indicators and Indices, https://library.wmo.int/doc_num.php?explnum_id=3057.

ADD new entries in Code Table 4.10

|Code number|	name|
|--|--|
|102|	Index processing|

Note: For code number 102 the drought index encoded in the message is specified by the table entries from discipline 0 and parameter category 22 with the corresponding parameter number. The statistical processing period of the drought index is defined by the keys “length of time range” and "indicator of unit of time for the increment”.

ADD new entries in Code Table 4.101Type of relationship to reference dataset

|Code number	|name|
|--|--|
|23|	Standardised drought index (see Note 5)|
|24-191|	Reserved|

Note 5: WMO proposed indices (https://library.wmo.int/doc_num.php?explnum_id=3057). The index is specified by setting discipline and parameter category / number to the specific index to be encoded. Drought indicators are calculated over different time ranges, prescribed by the keys lengthOfTimeRange and indicatorOfUnitForTimeRange in the templates 4.107, 4.108, 4.109 and 4.112. All standardised drought indices are calculated according to WMO guidelines of the SPI (https://library.wmo.int/doc_num.php?explnum_id=7768).

ADD new entries in Code Table 4.102 Statistical processing of reference period

|Code number	|Name|
|--|--|
|21|	Index based on Normal distribution|
|22|	Index based on Log-Normal distribution|
|23|	Index based on Generalized Log-Normal distribution|
|24|	Index based on Gamma distribution|
|25|	Index based on Logistic distribution|
|26|	Index based on Log-Logistic distribution|
|27|	Index based on Generalized Logistic distribution|
|28|	Index based on Weibull distribution|
|29|	Index based on Generalized Extreme Value distribution|
|30|	Index based on Pearson III distribution|
|31|	Index based on empirical distribution|
|32-191|	Reserved|

### Comments
https://community.wmo.int/en/activity-areas/agmp

### Requestor(s)

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, 

### Expected impact of change

None

### Collaborators

Jessica Keune (ECMWF)

### References
[Handbook of Drought Indicators and Indices (WMO-No. 1173)](https://library.wmo.int/idurl/4/55169)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023 notes: 
Sebastien presented this at the meeting, it remains TBD...

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023 notes: 
Proposal is still in progress; Sebastien talked about a simpler option of just creating a distinct code table (e.g. 4.10) and not try to create new templates; Sibylle noted that it could be generalized;

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023) notes: 

Sebastien introduced the proposal and team is invited to review; Sibylle recommends generalizing the proposal by removing "Drought" from name;

**Comment by sebvi** [comment]
I have updated the proposal to take into account @SibylleK 's suggestion. thank you

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
Sebastien updated the branch; Will also remove "drought" from 4.10;

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

ready

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024](https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024) notes:

Anna requested some editorial changes;
