### ISSUE TITLE
new probability templates for large ensemble

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#224]
### Initial request

This proposal extends the existing templates 4.5 and 4.9 for probability forecasts by additional keys which allow to encode the ensemble size of large ensembles and the type of ensemble forecast from which the probabilities are derived.

A branch with an implementation of this template is accessible under:
https://github.com/ecmwf/eccodes/tree/feature/ECC-1705-probabilitiesWithFocalStats

### Amendment details

ADD the following templates entries in code table 4.0.

|Code	|Name|
|--|--|
|119	|Probability forecasts from large ensembles at a horizontal level or in a horizontal layer at a point in time
|120	|Probability forecasts from large ensembles at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval

ADD Template 4.119 - Probability forecasts from large ensembles at a horizontal level or in a horizontal layer at a point in time.

|Octet	|Number of octets	|Description|
|--|--|--|
|10|	1|	Parameter Category (see code table 4.1)|
|11|	1|	Parameter Number (see code table 4.2)|
|12|	1|	Type of Generating Process (see code table 4.3)|
|13|	1|	Background Process|
|14|	1|	Generating Process Identifier|
|15-16|	2|	Hours After Data Cut-off|
|17|	1|	Minutes After Data Cut-off|
|18|	1|	Indicator of Unit of Time Range (see code table 4.4)|
|19-22|	4|	Forecast Time|
|23|	1|	Type of First Fixed Surface (see code table 4.5)|
|24|	1|	Scale Factor of First Fixed Surface|
|25-28|	4|	Scaled Value of First Fixed Surface|
|29|	1|	Type of Second Fixed Surface (see code table 4.5)|
|30|	1|	Scale Factor of Second Fixed Surface|
|31-34|	4|	Scaled Value of Second Fixed Surface|
|35|	1|	Type of ensemble forecast (see Code table 4.6)|
|36-39|	4|	Number of forecasts in ensemble|
|40|	1|	Forecast Probability Number|
|41|	1|	Total Number of Forecast Probabilities|
|42|	1|	Probability Type (see code table 4.9)|
|43|	1|	Scale Factor of Lower Limit|
|44-47|	4|	Scaled Value of Lower Limit|
|48|	1|	Scale Factor of Upper Limit|
|49-52|	4|	Scaled Value of Upper Limit|
 
ADD Template 4.120 - Probability forecasts from large ensembles at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval.

|Octet|	Number of octets|	Description|
|--|--|--|
|10|	1|	Parameter Category (see code table 4.1)|
|11|	1|	Parameter Number (see code table 4.2)|
|12|	1|	Type of Generating Process (see code table 4.3)|
|13|	1|	Background Process|
|14|	1|	Generating Process Identifier|
|15-16|	2|	Hours After Data Cut-off|
|17|	1|	Minutes After Data Cut-off|
|18|	1|	Indicator of Unit of Time Range (see code table 4.4)|
|19-22|	4|	Forecast Time|
|23|	1|	Type of First Fixed Surface (see code table 4.5)|
|24|	1|	Scale Factor of First Fixed Surface|
|25-28|	4|	Scaled Value of First Fixed Surface|
|29|	1|	Type of Second Fixed Surface (see code table 4.5)|
|30|	1|	Scale Factor of Second Fixed Surface|
|31-34|	4|	Scaled Value of Second Fixed Surface|
|35|	1|	Type of ensemble forecast (see Code table 4.6)|
|36-39|	4|	Number of forecasts in ensemble|
|40|	1|	Forecast Probability Number|
|41|	1|	Total Number of Forecast Probabilities|
|42|	1|	Probability Type (see code table 4.9)|
|43|	1|	Scale Factor of Lower Limit|
|44-47|	4|	Scaled Value of Lower Limit|
|48|	1|	Scale Factor of Upper Limit|
|49-52|	4|	Scaled Value of Upper Limit|
|53-54|	2|	Year of end of overall time interval|
|55|	1|	Month of end of overall time interval|
|56|	1|	Day of end of overall time interval|
|57|	1|	Hour of end of overall time interval|
|58|	1|	Minute of end of overall time interval|
|59|	1|	Second of end of overall time interval|
|60|	1|	n - number of time range specifications describing the time intervals used to calculate the statistically processed field|
|61-64|	4|	Total number of data values missing in statistical process|
|	|	|65 - 76 Specification of the outermost (or only) time range over which statistical  processing is done|
|65|	1|	Statistical process used to calculate the processed field from the field at each time increment during the time range (see code table 4.10)|
|66|	1|	Type of time increment between successive fields used in the statistical processing (see code table 4.11)|
|67|	1|	Indicator of unit of time for time range over which statistical processing is done (see code table 4.4)|
|68-71|	4|	Length of the time range over which statistical processing is done, in units defined by the previous octet|
|72|	1|	Indicator of unit of time for the increment between the successive fields used (see code table 4.4)|
|73-76|	4|	Time increment between successive fields, in units defined by the previous octet|
|	|	|77 - nn These octets are included only if n > 1, where nn = 65+ 12 x n|
|77-88|	12|	As octets 65 to 76, next innermost step of processing|
|89-nn|	n/a|	Additional time range specifications, included in accordance with the value of n.  Contents as octets 65 to 76, repeated as necessary|

Add to table 4.7: Derived forecast

|Code	|name|
|--|--|
|10|	Variance of all ensemble members|

### Requestor(s)

Robert Osinski (ECMWF)
Sebastien Villaume (ECMWF)

### Stakeholder(s)

ECMWF + member states

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, GRIB templates in section 4

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023 notes: 
Sebastien introduced the proposal; team agrees to proposal; there are samples in the eccodes branch linked to in the issue summary;

**Comment by sebvi** [comment]
we need a branch for this proposal

**Comment by amilan17** [comment]
done

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
Sebastien copied the previous templates and increased the number of octets and will have a branch ready for tomorrow;

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

Sebastien will add samples;

**Comment by sebvi** [comment]
I am adding a sample for template 4.120

[GRIB2_224.zip](https://github.com/wmo-im/GRIB2/files/13886657/GRIB2_224.zip)

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024](https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024) notes:

Anna provided an editorial review; @SibylleK to validate samples

**Comment by SibylleK** [comment]
For a pure technical validation, I was able to read the entries in section 4 of the GRIB example file PDTN_120.grib2 with a DWD GRIB reader software.
The entries were the same as in an output of eccodes grib_dump.
This means that the proposal has been validated.
