### ISSUE TITLE
new hydrology parameters in code Table 4.2

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#227]
### Initial request

ECMWF is requesting new hydrological parameters to support the development of our next model upgrades and to support Destination Earth activity.

### Amendment details

ADD in Code Table 4.2

Product discipline 1 - Hydrological products, parameter category 2: inland water and sediment properties

|Parameter number |name|Unit| Description |
|--|--|--|--|
|17|Floodplain depth|m| Depth of water at the junction between the river and the floodplain. This variable does not include the main river channel. |
|18|Floodplain flooded fraction|Proportion| The fraction of the grid cell that is flooded. If it's 0, there is no permanent water or floodplain water in that cell. If the value is 1, it means the entire cell is flooded (includes rivers). This variable does not include the main river channel. It's an area divided by the total area of the grid cell. |
|19|Floodplain flooded area|m2| The area of the grid cell that is temporarily flooded (i.e. covered with water). This does not include the main river channel. |
|20|River fraction|Proportion| This is the permanent water area divided by the grid cell area. |
|21|River area|m2| The area of the grid cell that contains the permanent water area (i.e. river). This does not change in time. | 
|22|Fraction of river coverage plus river related flooding|Proportion| The fraction of the grid cell that is flooded. If the value is 1, the whole cell is flooded. If it's 0, there is no permanent water or flood in that cell. This does include the main river channel. |
|23|Area of river coverage plus river related flooding|m2| The area of the grid cell that is temporarily flooded (i.e. covered with water). This does include the main river channel. |

Product discipline 10 - Oceanographic products, parameter category 0: waves

|Parameter number|name|Unit|
|--|--|--|
|98|Goda peakedness factor|Numeric|

 

### Requestor(s)

Robert Osinski (ECMWF)
Sebastien Villaume (ECMWF)

### Stakeholder(s)

ECMWF
Destination Earth

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 1, category 2
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 10, category 0

### Expected impact of change

None

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.17.18.October.2023) notes: 

Sebastien introduced; team agrees to proposal

@sebvi will add definitions

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
Descriptions are added to the proposal, but it won't go into the publication or CSVs; Branch is ready for validation;
