### ISSUE TITLE
new fire weather parameter in Code Table 4.2, Discipline 2

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/GRIB2#229]
### Initial request

The NCEP Environmental Modeling Center requests a new entry in GRIB2 Code Table 4.2.

### Amendment details

New entry in Code table 4.2, Discipline 2 (Land surface products), Category 4 (Fire weather products):

Name | Discipline | Category | Parameter | Units
-- | -- | -- | -- | --
Fire radiative power | 2 | 4 | 36 | W

### Requestor(s)

Jeff Ator - U.S. NWS/NCEP/EMC @jbathegit
Andrew Benjamin - U.S. NWS/NCEP/EMC @AndrewBenjamin-NOAA
Eric James - U.S. OAR/ESRL/GSL @EricJames-NOAA

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 2, category 4

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes: 
Jeff introduced the proposal; Sebastien provided feedback (see his comment)

**Comment by sebvi** [comment]
Dear @jbathegit , thank you for your proposal. I have a question/comment:

is your parameter a "mean" over a time period? The units, W ( or equivalently J s-1) suggests that it is a rate. 
If it is indeed a "mean rate", I would suggest to propose "Fire radiative power" instead (if it does not already exist), with same units, then use the key "type of statistical post processing" to indicate an average over time, and then use the key for the "length of time range" to specify over how long the mean was computed.

**Comment by jbathegit** [comment]
Good question Sebastien!

@AndrewBenjamin-NOAA, @EricJames-NOAA can you confirm that the mean is over a time period, and if so we could just change the name to "Fire radiative power" and handle the mean component separately, as @sebvi suggests?

**Comment by EricJames-NOAA** [comment]
@jbathegit the mean is over a time period.  And actually, with our latest model, the Rapid Refresh Forecast System (RRFS), it is an hourly FRP.  So I think it would make sense to get rid of the "mean" entirely.  We can handle it separately if needed for individual applications.

**Comment by amilan17** [comment]
@jbathegit the branch is now available.

**Comment by jbathegit** [comment]
Thanks @amilan17.  I just updated the branch.

**Comment by sebvi** [comment]
Hi @jbathegit , 

I have discussed with our fire experts and we have one question: 

is your parameter representing the value for the entire grid box or is it a grid box area weighed parameter? one would be a value in absolute Watts (W) wrt to a value in watts per square meter (W m-2) which is often use as well.

**Comment by jbathegit** [comment]
> Hi @jbathegit ,
> 
> I have discussed with our fire experts and we have one question:
> 
> is your parameter representing the value for the entire grid box or is it a grid box area weighed parameter? one would be a value in absolute Watts (W) wrt to a value in watts per square meter (W m-2) which is often used as well. with the relationship:
> 
> absolute value (W) = area weighed value (W m-2) * area (m2)

@sebvi thanks again to you and your colleagues for your thorough review of the proposal!

@AndrewBenjamin-NOAA, @EricJames-NOAA could you please clarify?  We have the units currently set to W for this new parameter, but we can change it to W m-2 if that's indeed more appropriate for what you'll be reporting.  Please let us know - thanks!

**Comment by EricJames-NOAA** [comment]
> > Hi @jbathegit ,
> > I have discussed with our fire experts and we have one question:
> > is your parameter representing the value for the entire grid box or is it a grid box area weighed parameter? one would be a value in absolute Watts (W) wrt to a value in watts per square meter (W m-2) which is often used as well. with the relationship:
> > absolute value (W) = area weighed value (W m-2) * area (m2)
> 
> @sebvi thanks again to you and your colleagues for your thorough review of the proposal!
> 
> @AndrewBenjamin-NOAA, @EricJames-NOAA could you please clarify? We have the units currently set to W for this new parameter, but we can change it to W m-2 if that's indeed more appropriate for what you'll be reporting. Please let us know - thanks!

@jbathegit the units should be W.  The values are not weighted by grid box area.  Thanks!

**Comment by amilan17** [comment]
branch is consistent with proposal

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.21.29.November.2023) notes:

issue is valid
