### ISSUE TITLE
new precipitation type flag in Code Table 4.201

### ISSUE THREAD

**Issue by feggleton** [wmo-im/GRIB2#238]
### Initial request

The UK Met Office requests a new entry in GRIB2 Code Table 4.201 Precipitation Type Flags
New entry in Code Table 4.201 to differentiate between hail sizes. The Met Office requires a flag for large hail, would like to discuss how this could be achieved, if 'large hail' is added as a new code, would we need to change the name of 'hail' to 'small hail'? 

Title_en | SubTitle_en | CodeFlag | Value | MeaningParameterDescription_en | Note_en | noteIDs | UnitComments_en | Status
-- | -- | -- | -- | -- | -- | -- | -- | --
Precipitation type |   | 13? |   | Large hail |   |   |   | 

### Amendment details
Add two new codes for hail with size parameters.

|title|code|meaning|				
|--|--|--|
|Precipitation type		|10		|Hail				
|Precipitation type		|11		|Drizzle				
|Precipitation type		|12		|Freezing drizzle				
|Precipitation type		|13		|**Hail (less than 5 mm)**				
|Precipitation type		|14		|**Hail (greater than or equal to 5 mm)**				

### Requestor(s)

Francesca Eggleton - UK Met Office @feggleton
Lara Gunn - UK Met Office @laragunn

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 5

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
@feggleton @laragunn are you available to join one of our meeting on 2, 14, or 15 of May to introduce this proposal? If so, will you please email me at amilan@wmo.int.

**Comment by sebvi** [comment]
Dear @feggleton,  thank you for this proposal. 

I don't think that we can rename the existing "hail" entry to "small hail" because it will invalidate any existing data. If the Met Office needs both "small hail" and "large hail", then I would recommend to add both to the table. We can then have a note attached to the table to explain that the existing  "hail" entry is any size while small/large hail can be used to discriminate the size. Furthermore, one should either use "hail" or "small/large hail" but not both options at the same time.

**Comment by feggleton** [comment]
Thanks @sebvi yes you are right, that was my mistake on backwards compatibility. I think that is a good suggestion. I will go back to my team and we can discuss in the meeting.

**Comment by feggleton** [comment]
I've gathered together different definitions which might help with this decision, there are varying definitions and it's not clear cut about the sizes.

WMO defines: Graupel 2-5mm, small hail 'may approach or even exceed 5mm', hail 5-50mm.

ICAO (aviation): "Small hail (METAR code GS) is hail or graupel of less than 5 mm in diameter. True hail (METAR code GR) is hail of 5 mm or more in diameter." ie. small hail <5mm, true hail >=5mm.

European Severe Storms Laboratory guidance: small hail 0-19mm, large hail 20-49mm, very large hail >=50mm

As Graupel is already in the table and not in question, I don't think we need to amend this definition. From the above information, I would suggest we add to the table, hail (<5mm) and hail (>=5mm). We have previously discussed in the meeting about remove the naming of small and large, happy to discuss further. @laragunn please comment if you'd like to suggest something else based on your knowledge.

I would welcome comments to discuss this further. Thanks.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes: 
- team reviewed latest comments and agreed with the suggestion to "add to the table, hail (<5mm) and hail (>=5mm)" 
@sebvi will update the branch

**Comment by amilan17** [comment]
> https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes:
> 
> * team reviewed latest comments and agreed with the suggestion to "add to the table, hail (<5mm) and hail (>=5mm)"
>   @sebvi will update the branch

@sebvi will you be able to update the branch soon?

**Comment by amilan17** [comment]
|title|code|meaning|				
|--|--|--|
|Precipitation type		|10		|Hail				
|Precipitation type		|11		|Drizzle				
|Precipitation type		|12		|Freezing drizzle				
|Precipitation type		|13		|**Hail (less than 5 mm)**				
|Precipitation type		|14		|**Hail (greater than or equal to 5 mm)**

**Comment by feggleton** [comment]
That is useful, thank you.
