### ISSUE TITLE
convective rain and snow specific water content in Code Table 4.2

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#24]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-24

# Summary and purpose
ECMWF is requesting 2 new parameters to represent convective rain and snow specific water content.
 
# Action proposed
ECMWF kindly asks the team to review the proposal and accept it during the next session.

# Discussions
ECMWF is developing the possibility to generate fields of specific water contents (kg/kg) for convective rain and snow.

These 2 parameters are equivalent to the existing specific rain and snow water content parameters:

-   specific rain water content   kg/kg  discipline=0 category=1 code=85
-   specific snow water content   kg/kg  discipline=0 category=1 code=86

 It is unclear if the two parameters above represents only large-scale, non convective specific water content or the total (large scale + convective).
i
We would like to request two new parameters  :
  specific rain water content (convective)  kg/kg 
  specific snow water content (convective)  kg/kg 

# Detailed proposal
add a new entries in Code Table 4.2, discipline 0, category 1:
| Code | Name  | Units  |
|:-:|:-:|:-:|
| 124 | specific rain water content (convective) | kg/kg |
| 125 | specific snow water content (convective) | kg/kg |
 
This proposal takes into account issues #15  and #20 to avoid code entry clash.

**Comment by efucile** [comment]
@sebvi  should they be 
rain specific water content
snow specific water content
?

**Comment by sebvi** [comment]
I thought so as well @efucile but entry 83-86 in the same table were using that strange ordering (as mentioned in my proposal).
I am happy to change because it is more correct but I would then propose to do an editorial change to entries 83-86 to stay consistent

**Comment by efucile** [comment]
-- | -- | -- | -- | -- | -- | -- | --
-- | -- | -- | -- | -- | -- | -- | --
Parameter number by product discipline and parameter category | Product discipline 0 - Meteorological products, parameter category 1: moisture | 83 |   | Specific cloud liquid water content |   | kg/kg | Operational

  | Parameter number by product discipline and parameter category | Product discipline 0 - Meteorological products, parameter category 1: moisture | 84 |   | Specific cloud ice water content |   | kg/kg | Operational
  | Parameter number by product discipline and parameter category | Product discipline 0 - Meteorological products, parameter category 1: moisture | 85 |   | Specific rainwater content |   | kg/kg | Operational
  | Parameter number by product discipline and parameter category | Product discipline 0 - Meteorological products, parameter category 1: moisture | 86 |   | Specific snow water content |   | kg/kg | Operational
  | Parameter number by product discipline and parameter category | Product discipline 0 - Meteorological products, parameter category 1: moisture | 87 |   | Stratiform precipitation rate

**Comment by chenxiaoxia2019** [comment]
@sebvi  Hi, Sebastien.  A new branch has been created. As you mentioned in #issue 20, it is common to see clashes when it comes to the parameter. So it is with this one. I proposed to change from 124 to 144, from 125 to 145. Is it okay? FYI, 
Code Table 4.2
#24 
124 changed to 144
125 changed to 145

#17
122-127 

#15
122 changed to 143

#20
123 changed to 128

**Comment by sebvi** [comment]
@chenxiaoxia2019 The entries and the branch seem ok to me. However, while checking, I noticed that most of the parameters in the table are specified in kg kg-1 (instead of kg/kg). Maybe we should change the 2 entries to units kg kg-1
More generally we should do a consistency editorial change and change all units containing "/" to the negative exponent notation (in a separate branch only addressing this)

**Comment by amilan17** [comment]
change units of these entries to kg kg-1 @chenxiaoxia2019

**Comment by amilan17** [comment]
SUMMARY: Add entries, 144 & 145, to Code Table 4.2, discipline 0, category 1.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
