### ISSUE TITLE
Create GH actions to generate machine readable codes

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#242]
### Details

Currently, there are no GH actions on this repo and it would be helpful if they were there. 

I think the actions should follow the logic as determined in https://github.com/wmo-im/CCT/issues/197.

### Requestor

Anna Milan (WMO), @amilan17

**Comment by antoinemerle** [comment]
Hi @amilan17 , That one is under-investigation.

I need to understand if we need a similar xml generation script as made for CCT and BUFR.

I am working on it
