### ISSUE TITLE
Deprecate template 4.44, create rectified version as template 4.50

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#245]
### Initial request

The template 4.44, Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol is marked as operational, however it is recommended not to use this template: "PDT 4.48 Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for optical properties of aerosol should be used instead with the optical wavelength range set to missing". 
The issue with template 4.44 is that the forecast time has only 2 octets instead of the usual 4 octets. This means that deterministic forecasts for aerosols use the template 4.48 which includes additionally keys for the optical wavelength (all set to missing to ignore them) while for probabilistic aerosol forecasts the aerosol-only template 4.45 can be used. This leads to a discrepancy in the layout of the same data coming from deterministic and probabilistic model runs. 

 
We propose to deprecate the template 4.44 and  properly create a new template 4.50 (instead of 4.48 with keys set to missing) with the forecast time having 4 octets as it is the case in the corresponding probabilistic aerosol template 4.45. 

### Amendment details

DEPRECATE template 4.44 and CREATE a corrected version as template 4.50. 

ADD to code table 4.0 - Product definition template number 

Code | Description
-- | --
50 | Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol

CREATE Template 4.50  - Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for aerosol 

Octet | Number of octets | Description
-- | -- | --
10 | 1 | Parameter Category (see code table 4.1)
11 | 1 | Parameter Number (see code table 4.2)
12-13 | 2 | Aerosol Type (see common code table C-14)
14 | 1 | Type of Size Interval (see code table 4.91)
15 | 1 | Scale Factor of First Size
16-19 | 2 | Scaled Value of First Size
20 | 1 | Scale Factor of Second Size
21-24 | 2 | Scaled Value of Second Size
25 | 1 | Type of Generating Process (see code table 4.3)
26 | 1 | Background Process
27 | 1 | Generating Process Identifier
28-29 | 2 | Hours After Data Cut-off
30 | 1 | Minutes After Data Cut-off
31 | 1 | Indicator of Unit of Time Range (see code table 4.4)
32-35 | 4 | Forecast Time
36 | 1 | Type of First Fixed Surface (see code table 4.5)
37 | 1 | Scale Factor of First Fixed Surface
38-41 | 4 | Scaled Value of First Fixed Surface
42 | 1 | Type of Second Fixed Surface (see code table 4.5)
43 | 1 | Scale Factor of Second Fixed Surface
44-47 | 4 | Scaled Value of Second Fixed Surface

### Requestor(s)

ECMWF

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.0 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.44 (deprecate)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.48 (create)

### Expected impact of change

MEDIUM

### Collaborators

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

**Comment by amilan17** [comment]
[2024-05-02](https://github.com/wmo-im/CCT/wiki/Teleconference.02.May.2024) notes:
Sebastien presented the proposal; Sibylle proposed a different solution with entries set to missing instead (@SibylleK can you add details here?);

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes: 
Sebastien summarized the two options for moving forward (new template or set values to missing in existing template);  
DECISION: move forward with new template;

**Comment by sebvi** [comment]
branch created and updated according to DECISION

**Comment by sebvi** [comment]
You can find a branch of ecCodes implementing template 4.50 here: [feature/ft2024-2_245 ](https://github.com/ecmwf/eccodes/tree/feature/ft2024-2_245)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes: 
@SibylleK will review the samples

**Comment by amilan17** [comment]
> https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes: @SibylleK will review the samples

@SibylleK have you had a chance to validate the samples yet?

**Comment by SibylleK** [comment]
@amilan17 the template is validated.

I was able to decode the sample grib with a DWD GRIB reading software using the definitions of the branch.
The values in section 4 are the same as in eccodes grib_dump.
