### ISSUE TITLE
Code table 4.9: add an entry to encode a probability based on a quantile distribution instead of based on a threshold

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#247]
### Initial request

 The templates “4.5 Probability forecasts at a horizontal level or in a horizontal layer at a point in time” and “4.9 Probability forecasts at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval” can be used to encode probability forecasts based on one or two threshold criteria. For instance, one can encode the probability of total precipitation of "at least 5mm" in the last 24h.

We would like to propose a new entry in the code table 4.9 to extend the applicability of the templates for probability forecasts with the probability of the parameter being within a certain quantile. This solution is not "ideal" since it slightly repurpose the meaning of the "lower" and "upper" limit in the templates but it has the advantage to not create completely new templates just to rename lower and upper limits to more genric terms.

### Amendment details

Add to code table 4.9 – Probability type
Code | Description
-- | --
10 | Probability of event within the quantile of the probability distribution function (see Note)

Note: When using entry 10, the lower limit is used to encode the quantile q (must be an integer between 0 and Q) while the upper limit is used to encode the total number of quantiles Q. This defines the probability of the parameter falling within quantile q. For instance, to encode the probability of falling within the 10th percentile, then q=10 and Q=100; to encode the probability of falling within the 1st tercile, then q=1 and Q=3.

### Requestor(s)

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Codes (WMO-No. 306), Volume I.2, GRIB code table 4.9 (update)

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.14.May.2024 notes:
Sebastien introduced the proposal;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes:
team reviewed

**Comment by sebvi** [comment]
@amilan17:  while updated Code table 4.9, I noticed that the note 3 was not updated to its final value and still read as "225d"

**Comment by sebvi** [comment]
branch created and updated

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes: 
branch is ready for validation; Sebastien will add samples next week

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
@sebvi update PDF acronym in proposal and branch
