### ISSUE TITLE
Code table 4.101: new entry in code table 4.101 to extend the usage of templates 4.105, 4.106, 4.107 and 4.112

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#248]
### Initial request

For the templates 4.105, 4.106, 4.107 and 4.112, ECMWF would like to propose a new code table entry in code table 4.101 for a newly introduced index at ECMWF: Crossing Point Forecast index (CPF). This new index is described in "Ben Bouallègue, Z. (2021). On the verification of the crossing-point forecast. Tellus A: Dynamic Meteorology and Oceanography, 73(1), 1–10. "https://doi.org/10.1080/16000870.2021.1913007

### Amendment details

ADD to code table 4.101 – Type of relationship to reference dataset 

Code | Description
-- | --
24 | Crossing Point Forecast (CPF) (see Note)

Note: Ben Bouallègue, Z. (2021). On the verification of the crossing-point forecast. Tellus A: Dynamic Meteorology and Oceanography, 73(1), 1–10. https://doi.org/10.1080/16000870.2021.1913007 

### Requestor(s)

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.101 (update)

### Expected impact of change

LOW

### Collaborators

Zied Ben Bouallègue (ECMWF)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.14.May.2024 notes:
Sebastien introduced the proposal

**Comment by sebvi** [comment]
changed entry from 22 to 24 as I realised we added entries 22 and 23 during the previous fast track

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes: 
branch is ready for validation;
