### ISSUE TITLE
Code table 1.4, 4.3 and 4.6: Adding new entries to better describe type of forecasting

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#249]
### Initial request

In the context of several, related developments, ECMWF is requesting new entries in several code table to support the new products.

For data which have the only purpose to demonstrate the data layout, for example as demo data for new templates proposed in a WMO Fast-track, we request a new entry for identifying sample data in code table 1.4. In the same table, EWCMWF is also requesting a specific entry to clearly label Machine learning based products.  

Different forecast products with forecast skills on different forecast horizons are combined and weighted to produce a seamless composite forecast product. In this context, ECMWF is requesting a new entry "blended forecasts" in code table 4.3. 

Finally, ECMWF is proposing to extend code table 4.6 with new entries to facilitate the identification of the different type of peturbations to produce perturbed forecasts.

### Amendment details

ADD to code table 1.4 Type of data 
Code | Description
-- | --
9 | Experimental data (see Note)
10 | ML based forecast (see Note)

Note: 9 – Data for demonstrational purposes only; 10 – forecast from Machine Learning (ML) model.

ADD to code table 4.3 Type of generating process 
Code | Description
-- | --
22 | Blended forecast (see note)

Note: Combination of different forecast products to produce a smooth, continuous forecast by applying weights to each individual prediction system which depend on the lead time and forecast skill (e.g. seamless prediction using nowcasting to short-range to medium-range). 

ADD to code table 4.6 Type of ensemble forecast
Code | Description
-- | --
5 | Unperturbed forecast
6 | Perturbed forecast
7 | Initial conditions perturbations (see Note)
8 | Model physics perturbations (see Note)
9 | Initial conditions + model physics perturbations (see Note)

Note: 7 – Ensemble members are initialised from different initial conditions; 8 – model physics are perturbed e.g., with methods like SPPT, SPP, SKEB, etc.; 9 – combination of 7and 8. 

### Requestor(s)

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 1.4 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.3 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.6 (update)

### Expected impact of change

LOW

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.14.May.2024 notes:
Sebastien introduced the proposal

**Comment by sebvi** [comment]
proposal updated to use "experimental data". Branch created and updated

**Comment by amilan17** [comment]
@sebvi I think the branch has not been updated for 'experimental' and the notes are missing.

**Comment by amilan17** [comment]
@sebvi I added the notes and changed sample to example.
