### ISSUE TITLE
New GRIB2 Code Table 4.2 entries for the physical atmospheric properties of seeing and sky transparency

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/GRIB2#25]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-25

# Summary and purpose
New GRIB2 Code Table 4.2 entries for the physical atmospheric properties of seeing and sky transparency

# Action proposed
The tables annexed herewith contain proposed additions to Table 4.2 of the GRIB2 section of the Manual on Codes, for new physical atmospheric forecast parameters, namely sky transparency (humidity component) and seeing.  Interpretation notes are included.

# Discussions

Initially discussed at Offenbach 2018 [report](http://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-CM_Offenbach2018/Report/Report_IPET-CM-II_Offenbach_annex.docx)

Seeing and transparency diagnostic forecast parameters have been produced for many years from NWP output at the Canadian Meteorological Centre. They are popular with amateur and professional astronomers, and were found useful in other applications where it is important to characterize the properties of sky light at a given time in the future.  While up to now these fields were made available as non-georeferenced raster graphics, there is now a requirement to make these fields available as georeferenced data and as GRIB files.
Seeing is the term used in astronomy to qualify the steadiness or turbulence of the atmosphere. Turbulence causes rapid and random fluctuations of the optical path through the atmosphere. The twinkling of stars, for example, occurs in poor seeing conditions. The  data product is a categorical index that provides a qualitative indication of transparency conditions (i.e. from "excellent" to "very poor").
Sky transparency qualifies the effect of atmospheric composition on the viewing experience. Light travelling through the atmosphere is subject to scattering, the amount of which depends on the presence of water vapour, aerosols or other constituents. Ideal transparency conditions produce a black night sky conducive to viewing faint astronomical objects, almost like being in outer space. In poor transparency conditions, which may occur even in cloud-free conditions, the deep sky background is grayish (not black), faint details are washed out and contrast is reduced.
 The data product is a categorical index that provides a qualitative indication of seeing conditions (i.e. from "excellent" to "very poor").
More information can be found in these pages:

http://www.skyandtelescope.com/astronomy-blogs/imaging-foundations-richard-wright/seeing-vs-transparency-difference/

https://weather.gc.ca/astro/seeing_e.html 

https://weather.gc.ca/astro/transparence_e.html 

# Detailed proposal
Proposed new entries for Code Table 4.2
Product Discipline 0 – Meteorological products, parameter category 19: physical atmospheric properties 

Number | Parameter | Units
-- | -- | --
38 | Sky transparency index | Code Table   4.214
39 | Seeing index | Code Table   4.214
40-191 | Reserved |  
192-254 | Reserved for Local Use |  

Code Table 4.214   Environmental Factor Qualifier

Code Figure | Meaning
--|--
0 | Worst
1 | Very   poor
2 | Poor
3 | Average
4 | Good
5 | Excellent
6-190 | Reserved
191 | Unknown
192-254 | Reserved   for local use
255 | Missing

## Notes
(4) Parameter 38: 
In astronomy, Sky transparency means the effect on the viewing experience caused by the scattering of light through atmospheric water vapour, aerosols or other constituents. Ideal transparency conditions produce a black night sky conducive to viewing faint astronomical objects, almost like being in outer space. In poor transparency conditions, which may occur even in cloud-free conditions, the deep sky background is grayish (not black), faint details are washed out and contrast is reduced.

(5) Parameter 39: Seeing means the steadiness or turbulence of the atmosphere in the context of astronomical observation. Turbulence causes rapid random fluctuations of the optical path through the atmosphere. The twinkling of stars, for example, occurs in poor seeing conditions.

**Comment by sebvi** [comment]
Hello @tomkralidis , it seems to me that this proposal is the follow up of the proposal from Yves after IPET=CM II meeting. At that time, we had a long discussion (emails around June 21 2018 to June 25 2018). It seems that this proposal is the orginal one, not the revised version sent by Yves on June 25 2018.
As explained in these emails (I can forward them to you if you want), I am against the units chosen for sky transparency. I can attached to this issue the revised document sent by Yves.

**Comment by tomkralidis** [comment]
Hi @sebvi thanks for the info.  I've updated the proposal above with the revision.

**Comment by SibylleK** [comment]
The code-figures 36 and 37 meanwhile exist. It should be 38 and 39 instead.

**Comment by tomkralidis** [comment]
Thanks @SibylleK.  I've updated the proposal above with the revision.

**Comment by sebvi** [comment]
I am happy with the revised proposal. Thank you

**Comment by tomkralidis** [comment]
FYI I've updated the notes to align the updated parameter numbers.

**Comment by chenxiaoxia2019** [comment]
@tomkralidis Hi, Tom, a new branch regarding this issue has been created with new entries for Code Table 4.2. Could you please check it? Thanks.

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019.  When I review https://github.com/wmo-im/GRIB2/compare/issue-25, I do not see updates for Code Table 4.214, or is this elsewhere?

**Comment by chenxiaoxia2019** [comment]
> Thanks @chenxiaoxia2019. When I review httpsTh

**Comment by chenxiaoxia2019** [comment]
> Thanks @chenxiaoxia2019. When I review https://github.com/wmo-im/GRIB2/compare/issue-25, I do not see updates for Code Table 4.214, or is this elsewhere?
@tomkralidis Thanks, Tom. I missed updating this file. Now, the file has already been there: https://github.com/wmo-im/GRIB2/blob/issue-25/GRIB2_CodeFlag_4_215_CodeTable_en.csv

**Comment by tomkralidis** [comment]
Thanks @chenxiaoxia2019 , looks good to me.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
