### ISSUE TITLE
Code table 4.2 and 4.238: new source/sink entries in code table 4.238 and a new parameter in code table 4.2, discipline 0, category 20

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#250]
### Initial request

In the context of the development of the next atmospheric composition cycle, ECMWF is requesting a new parameter in code table 4.2 and several new entries to identify new source/sink origin.

### Amendment details

ADD to code table 4.2: Product discipline 0 - Meteorological products, parameter category 20: atmospheric chemical constituents
Parameter number | name | Unit
-- | -- | --
82 | Sink mass flux | [kg m-2 s-1]
83 | Source mass flux | [kg m-2 s-1]
84 | Volume-mean total column mixing ratio | [mol mol**-1]
112 | Absorption aerosol optical thickness | [Numeric]

ADD to code table 4.238 
Code | Description
-- | --
30 | Commercial buildings heating
31 | Residential heating
32 | Oil refineries and transformation industry
33 | Gas production
34 | Vegetation
35 | Biomass burning
36 | Settlements
37 | Soil
38 | Wild animals

### Requestor(s)

Sebastien Villaume (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 20 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.238 (update)

### Expected impact of change

LOW

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.14.May.2024 notes:
Sebastien introduced the proposal;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes: 
Sebastien introduced the new entries;

**Comment by sebvi** [comment]
branch created and update (forgot to chase colleagues about sink/source)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
branch is prepared, but there is still an outstanding question about sink/source;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
Sebastien will update the proposal and branch with sink and source.

**Comment by amilan17** [comment]
reopen to merge into FT branch instead of master
