### ISSUE TITLE
Code Table 4.1 and 4.2: new category for thermodynamical properties in discipline "land surface" and associated parameters

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#251]
### Initial request

ECMWF is proposing a new category under discipline 2 - Land surface to encode various thermodynamical properties (heat fluxes). This requires a new entry in Code table 4.1 for the new category and a new sub-table 4.2 discipline 2, category 7

Additional, ECMWF is requesting a new parameter in code table 4.2, discipline 0, category 4

### Amendment details

ADD new Category in Code Table 4.1 discipline 2 Thermodynamic properties
Code | Name
-- | --
7 | Thermodynamic properties

ADD new entries in Code table 4.2 discipline 2 category 7
Parameter number | name | Unit
-- | -- | --
0 | Heat net flux (see Note) | [W m-2]
1 | Latent heat net flux | [W m-2]
2 | Sensible heat net flux | [W m-2]

Note: Heat net flux is the sum of latent heat net flux and sensible heat net flux.

ADD new entry in Code table 4.2 discipline 0 category 4
Parameter number | name | Unit
-- | -- | --
62 | Direct normal short-wave radiation flux, clear sky (see note) | [W m-2]

Note: Normal flux is on a surface lifted to be normal to sun rays

ADD new entry in Code Table 4.2 discipline 0 category 19
Parameter number | name | Unit
-- | -- | --
51 | Visibility through precipitation | [m]

Add new entry in Code Table 4.2 discipline 3 category 1
Parameter number | name | Unit
-- | -- | --
24 | Cosine of the solar zenith angle |  [Numeric]

ADD new entries to Code Table 4.2 discipline 0  category 2
Parameter number | name | Unit
-- | -- | --
68 | Convective gust | [m s-1]
69 | Turbulent gust | [m s-1]

### Requestor(s)

Sebastien Villaume (ECMWF)
Matthew Griffith (ECMWF)

### Stakeholder(s)

ECMWF
EU - Destination Earth programme 

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.1 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 0, category 4 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2, discipline 2, category 7 (new subtable)

### Expected impact of change

LOW

**Comment by sebvi** [comment]
I have just added parameters that were forgotten

**Comment by sebvi** [comment]
branch created and updated

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes: 
Sebastien introduced the proposal

**Comment by amilan17** [comment]
@sebvi the note is missing

**Comment by SibylleK** [comment]
Maybe note (1) "By convention, the flux sign is positive if downwards" of Code table 4.2 is meant here.

In any case, I received a corresponding note from my colleague, that it would be good to clarify, that this note is also valid for these surface fluxes.

Another comment is, to consider to define these new entries as ".. total flux", as in future you might be able to diffferentiate between e.g. "due to exaporation" and "due to sublimation".

**Comment by mjg41** [comment]
Apologies the Note got lost somewhere along the way, it was intended to be:

> Note: Heat net flux is the sum of latent heat net flux and sensible heat net flux

The new entry **62** in Code table 4.2 discipline 0 category 4 should also be linked to Note ID 69.

Many thanks.

**Comment by amilan17** [comment]
@sebvi @mjg41 Is this the correct note for entry 62?
Parameter number | name | Unit
-- | -- | --
62 | Direct normal short-wave radiation flux, clear sky | [W m-2]

`69,Normal flux is on a surface lifted to be normal to sun rays.`

**Comment by sebvi** [comment]
parameters in Code Tables 4.2..0.4 and 4.2.0.5 don't specify "total" when it is assumed total so I would not make these parameters different for consistency.

**Comment by amilan17** [comment]
it was determined through email that it's not necessary to revise this proposal further.
