### ISSUE TITLE
Meteorological and hydrological hazards

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#254]
### Details

ECMWF would like to open a discussion on meteorological and hydrological hazards and how to eventually encode these in GRIB2. The aim of this discussion is to prepare a draft amendment for this fast track or the next one.

In the context of the Destination Earth EU initiative and in particular the "On Demand" Extreme Digital Twin activity (ODEDT), We need to be able to evaluate and encode the likelihood of a specific type of hazard for each grid box of a global domain. If a hazard is computed with a high likelihood in a region, it triggers a higher resolution regional model run over that region.

The initial list of hazards is the following:

- total precipitation
- CAPE shear
- 10 metre wind gust
- 10 metre wind speed
- heatwave
- heat stress
- poor air quality
- storm/cyclone/medicane (Mediterranean hurricane)
- fire
- snowstorm
- flashflood
- flooding
- wind energy ramping
- storm surge
- frost
- high gust events

We have identified a document produced by the UN Office for disaster risk reduction which classifies the various type of hazards: [UNDRR document](https://www.undrr.org/media/73913/download?startDownload=20240426) 

In this document many more hazards are defined, some are also meteorological but some other are not. 

Our initial idea is to create a new category under discipline 20 "Health and socioeconomic impacts". If we choose this option, is it better to be exhaustive and add all the identified hazards from the UN document above, all the meteorological and hydrological hazards only, or simply the short list of hazards above?

For each of these entries that are dimensionless and categorical, we would like to associate a table listing the various level of likelihood/degree of impact. We have several options here:
1. multiple tables adapted to each hazards
2. a unique table used by all entries of the new category with predetermined entries, managed by our TT team: low, moderate, high, etc.
3. the table are managed by each producing centres with the caveat of finding what the local table entries mean.

The table could look like this:
Code | Description
-- | --
0 | Undefined
1 | Likelihood High; Impact High (Red)
2 | Likelihood High; Impact Medium (Amber)
3 | Likelihood High; Impact Low (Yellow)
4 | Likelihood High; Impact Very Low (Green)
5 | Likelihood Medium; Impact High (Amber)
6 | Likelihood Medium; Impact Medium (Amber)
7 | Likelihood Medium; Impact Low (Yellow)
8 | Likelihood Medium; Impact Very Low (Green)
9 | Likelihood Low; Impact High (Amber)
10 | Likelihood Low; Impact Medium (Yellow)
11 | Likelihood Low; Impact Low (Green)
12 | Likelihood Low; Impact Very Low (Green)
13 | Likelihood Very Low; Impact High (Yellow)
14 | Likelihood Very Low; Impact Medium (Yellow)
15 | Likelihood Very Low; Impact Low (Green)
16 | Likelihood Very Low; Impact Very Low (Green)
192-254 | Reserved for local use
255 | Missing

We request the team to review this issue and provide guidance on the way forward.

### Requestor

Sebastien Villaume (ECMWF)
Matthew Griffith (ECMWF)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes: 
Sebastien introduced the proposal; all are invited to review and comment on it;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes:
Sebastien stated that this is a broader discussion topic and intended for a later date.

**Comment by sebvi** [comment]
We would like to proceed with this proposal. I would like to close this discussion and reopen a new issue for your final design
