### ISSUE TITLE
New GRIB table entry for describing probability

### ISSUE THREAD

**Issue by erget** [wmo-im/GRIB2#26]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-26

# Summary and purpose
This document proposes a new entry to GRIB table 4.16 “Quality value associated with parameter” to describe the probability of a geophysical parameter used in Product Definition Template 4.35 “Satellite product with or without associated quality values”.

# Action proposed
The meeting is requested to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
Several products used at EUMETSAT provide a confidence value associated with the geophysical product. It is proposed to update GRIB table 4.16 “Quality value associated with parameter” to include “Probability” for use in Product Definition Template 4.35 “Satellite product with or without associated quality values”.

This would be used e.g. in the EUMETSAT MSG Active Fires product with Product Definition Template 4.35 in order to indicate the probability of fire observed in a given pixel of the product.

# Detailed proposal
Add the following entry to GRIB Table 4.16:
| Code | Name |
| --- | --- |
| 5 | Probability |

**Comment by sebvi** [comment]
Hi @erget , I only have one question: will you ever need to encode a "probability of one of the other quality value" with or without threshold? For instance a probability of being within the standard deviation

**Comment by erget** [comment]
@sebvi never say never, but I don't see this anywhere on the horizon.

**Comment by chenxiaoxia2019** [comment]
@erget Hi, Daniel, a new branch for this issue has been created. Could you please check it? Thanks.

**Comment by erget** [comment]
@chenxiaoxia2019 thank you, I can see that the change to the branch is in line with the proposal. Fine from my side.

**Comment by amilan17** [comment]
SUMMARY: Add entry to Code Table 4.16.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
