### ISSUE TITLE
New parameters in Code Table 4.2 for Fire weather Forecasting

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#27]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-27

# Summary and purpose

ECMWF is requesting new Fire weather forecasting parameters.

# Action proposed

ECMWF kindly asks the team to review the proposal and accept it during the next session.

# Discussions

| Variable | Units | Description |
|:-:|:-:|:-:|
| Keetch-Byram drought index | NUMERIC | The Keetch-Byram drought index (KBDI) is a number representing the net effect of evapotranspiration and precipitation in producing cumulative moisture deficiency in deep duff and upper soil layers. It is a continuous index, relating to the flammability of organic material in the ground.The Keetch-Byram drought index attempts to measure the amount of precipitation necessary to return the soil to saturated conditions. |
| Drought factor (as defined by the Australian forest service )| NUMERIC | The Drought factor is a metric between 0 and 10 and represents the influence of recent temperatures and rainfall events on fuel availability. The Drought factor is partly based on the soil moisture deficit which is commonly calculated in using the Keetch-Byram drought index. |
| Rate of spread (as defined by the Australian forest service )| m/s | The rate of spread is a measure of the forward spread of fire on level to undulating ground. |
| Fire danger index (as defined by the Australian forest service )| NUMERIC | The Fire danger index is a metric related to the chances of a fire starting, its rate of spread, its intensity, and its difficulty of suppression. It is open ended however a value of 50 and above is considered extreme in most vegetation. |
| Spread component (as defined by the U.S Forest Service National Fire-Danger Rating System) | NUMERIC | The Spread component is a measure of the spead at which a headfire would spread. The spread component is numerically equal to the theoretical ideal rate of spread expressed in feet-per-minute however is considered as a dimensionless variable. The Spread component is expressed on an open-ended scale; thus it has no upper limit. |
| Burning index (as defined by the U.S Forest Service National Fire-Danger Rating System) | NUMERIC | The Burning Index measures the difficulty of controlling a fire. It is derived from a combination of Spread component (how fast it will spread) and Energy release component (how much energy will be produced). In this way, it is related to flame length, which, in the Fire Behavior Prediction System, is based on rate of spread and heat per unit area. This index is usually displayed in feet and scaled by a factor of 10. |
| Ignition component (as defined by the U.S Forest Service National Fire-Danger Rating System) | % | The Ignition component measures the probability a firebrand will require suppression action. Since it is expressed as a probability, it ranges on a scale of 0 to 100. An Ignition component of 100 means that every firebrand will cause a fire requiring action if it contacts a receptive fuel. Likewise an Ignition component of 0 would mean that no firebrand would cause a fire requiring suppression action under those conditions. |
| Energy release component (as defined by the U.S Forest Service National Fire-Danger Rating System) | Joule/m2 | The Energy release component is a number related to the available energy (British Thermal Unit) per unit area (square foot) within the flaming front at the head of a fire. Daily variations in Energy release component are due to changes in moisture content of the various fuels present, both live and dead. Since this number represents the potential "heat release" per unit area in the flaming zone, it can provide guidance to several important fire activities. It may also be considered a composite fuel moisture value as it reflects the contribution that all live and dead fuels have to potential fire intensity. The Energy release component is a cumulative or "build-up" type of index. As live fuels cure and dead fuels dry, the Energy release component values get higher thus providing a good reflection of drought conditions. The scale is open-ended or unlimited and, as with other National Forest Danger Rating System components, is relative. |

# Detailed proposal
add in Code Table 4.2, Discipline 2, Category 4:

| Code | Name  | Units  |
|:-:|:-:|:-:|
| 12 | Keetch-Byram drought index | NUMERIC |
| 13 | Drought factor (as defined by the Australian forest service )| NUMERIC |
| 14 | Rate of spread (as defined by the Australian forest service )| m/s |
| 15 | Fire danger index (as defined by the Australian forest service )| NUMERIC |
| 16 | Spread component (as defined by the U.S Forest Service National Fire-Danger Rating System) | NUMERIC |
| 17 | Burning index (as defined by the U.S Forest Service National Fire-Danger Rating System) | NUMERIC |
| 18 | Ignition component (as defined by the U.S Forest Service National Fire-Danger Rating System) | % |
| 19 | Energy release component (as defined by the U.S Forest Service National Fire-Danger Rating System) | Joule/m2 |

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien, a new branch has been created for this issue. Could you please check it? Thanks.

**Comment by sebvi** [comment]
@chenxiaoxia2019 it seems that entry 11 in discipline 2 category has disappeared from the table. The "reserved" entry has not been updated to remove entries 12-19 that are now taken by the new parameters

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien, thanks for your check. I have already updated all the changes as proposed. Could you please check it?

**Comment by sebvi** [comment]
@chenxiaoxia2019 It looks good now, thanks

**Comment by amilan17** [comment]
Approved by FT-2020-2.
