### ISSUE TITLE
New entries in Code Table 4.238

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#28]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-28

# Summary and purpose
ECMWF is requesting new entries in Code Table 4.238: Source or sink

# Action proposed
ECMWF kindly asks the team to review the proposal and accept it during the next session.

# Discussions
In a coming cycle, ECMWF is planning to implement/incorporate a more detailed scheme for emissions using new sources and splitting existing ones into more specific contributions.
We also would like to propose an editorial change to amend the present Code Table 4.238 by changing the entry "0 - reserved" by an entry representing "other" or "everything else". This is useful when one need to produce a field with all the remaining emissions (or depositions) that were not explicitly produced separately using the other entries of the table.

# Detailed proposal
change the following entry in Code Table 4.238
| code | Meaning|
|:-:|:-:|
|0 | Other|

add the following entries in Code Table 4.238
| code | Meaning|
|:-:|:-:|
| 12 | Elevated anthropogenic sources |
| 13 | Surface anthropogenic sources |
| 14 | Agriculture livestock |
| 15 | Agriculture soils |
| 16 | Agriculture waste burning |
| 17 | Agriculture (all) |
| 18 | Residential, commercial and other combustion |
| 19 | Power generation |
| 20 | Super power stations |
| 21 | Fugitives |
| 22 | Industrial process |
| 23 | Solvents |
| 24 | Ships |
| 25 | Wastes (solid and water) |
| 26 | Road transportation |
| 27 | Off-road transportation |

Note:

-  the sum of  entries 12 and 13 is equivalent to entry 4

- the sum of entries 14, 15 ,16  is equivalent to entry 17

**Comment by ckpan-hko** [comment]
How about windblown dust and mining industries?  Just a thought.

**Comment by SimonElliottEUM** [comment]
If the sum of 14, 15 and 16 = 17 this implies that the three types of agriculture are "mutually exclusive and collectively exhaustive", in other words there can be no other type of agriculture, and none of the types can co-exist. What about set-aside, or fallow pasture etc.

**Comment by sebvi** [comment]
@ckpan-hko We can add as many sources as we need. At the moment I am only requested what is needed at ECMWF because anyone is welcome to propose more entries.

@SimonElliottEUM you have a good point, entry 17 does not have to be prescriptive of what is included in it. It is meant to be a generic entry and perhaps the decision of what it includes is model dependant and should be left open. Thank you for your contribution.

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien. Could you please help check the new branch for this issue: https://github.com/wmo-im/GRIB2/tree/issue-28? Thanks.

**Comment by sebvi** [comment]
@chenxiaoxia2019 The branch contains the required change. BUT it also contains the changes for "mean direction" for the waves, which is a separate issue I believe. Maybe this branch was created from the branch of the "mean direction" fix instead of being created from master (or develop if we use a develop branch)

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien, I double checked with this issue. You are right, there should not be the change for "mean direction" for the waves. I have already updated it. Could you please check it? Thanks.

**Comment by sebvi** [comment]
@chenxiaoxia2019 It looks good now, thanks!

**Comment by chenxiaoxia2019** [comment]
@sebvi Hi, Sebastien, sorry to bother, could you please tell me where the notes to be added? "the sum of entries 12 and 13 is equivalent to entry 4" and "the sum of entries 14, 15 ,16 is equivalent to entry 17". At Code 4 and 17 respectively or elsewhere? Much appreiciated.

**Comment by sebvi** [comment]
Hi @chenxiaoxia2019 , I think that during the meeting we decided to drop the notes completely after a discussion with @SimonElliottEUM . He advocated that constraining the sum of components will prevent future addition of other components.

**Comment by chenxiaoxia2019** [comment]
@sebvi Thanks for your quick reply. That is very clear.

**Comment by SimonElliottEUM** [comment]
@chenxiaoxia2019 @sebvi I agree with Sebastien's recollections - we just need to supress the note

**Comment by amilan17** [comment]
Approved by FT-2020-2.
