### ISSUE TITLE
Alternative implementation of the Hazards indices describes in #285

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#291]
### Initial request

Following the discussion in issue [#254](https://github.com/wmo-im/GRIB2/issues/254) and [#285](https://github.com/wmo-im/GRIB2/issues/285), we will now also consider templates to implement the hazard indices in GRIB2. We will need ensemble and non-ensemble variants as well as instant and time-processed variants. Thus, the proposition below. We extend Table 4.0 to add the new templates, add a general hazard index parameter, add 4 new templates, an additional code table containing the hazard profiles, and an additional table for the value of the hazard index.

### Amendment details

ADD to code table 4.0 Product definition template number
Code | Description
-- | --
148 | Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for hazards
149 | Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for hazards
150 | Average, accumulation, extreme values or other statistically processed values, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for hazards
151 | Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval, for hazards

ADD to code table 4.2: Product discipline 20 - Health and socioeconomic impacts, parameter category X: ???
Code | Description | Unit
-- | -- | --
0 | Hazard index | (Code table 4.254)

TEMPLATE 4.148, Analysis or forecast at a horizontal level or in a horizontal layer at a point in time for hazards
Octet | Number of octets | Description
-- | -- | --
10 | 1 | Parameter Category (see code table 4.1)
11 | 1 | Parameter Number (see code table 4.2)
12-13 | 2 | Hazard Profile (see Code Table 4.253)
14-15 | 2 | Input process Identifier (See Note 1)
16-17 | 2 | Input originating centre (see Common Code table C-11 and Note 2)
18 | 1 | Type of Generating Process (see code table 4.3)
19 | 1 | Background Process
20 | 1 | Generating Process Identifier
21-22 | 2 | Hours After Data Cut-off
23 | 1 | Minutes After Data Cut-off
24 | 1 | Indicator of Unit of Time Range (see code table 4.4)
25- 28 | 4 | Forecast Time
29 | 1 | Type of First Fixed Surface (see code table 4.5)
30 | 1 | Scale Factor of First Fixed Surface
31-34 | 4 | Scaled Value of First Fixed Surface
35 | 1 | Type of Second Fixed Surface (see code table 4.5)
36 | 1 | Scale Factor of Second Fixed Surface
37-40 | 4 | Scaled Value of Second Fixed Surface

Notes:
* The input process identifier shall have the value of the "analysis or forecast process identifier" of the original GRIB message used as input of the post-processing.
* The input originating centre shall have the value of the "originating centre" of the original GRIB message used as input of the post-processing.

TEMPLATE 4.149 Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer at a point in time for hazards
Octet | Number of octets | Description
-- | -- | --
10 | 1 | Parameter Category (see code table 4.1)
11 | 1 | Parameter Number (see code table 4.2)
12-13 | 2 | Hazard Profile (see Code Table 4.253)
14-15 | 2 | Input process Identifier (See Note 1)
16-17 | 2 | Input originating centre (see Common Code table C-11 and Note 2)
18 | 1 | Type of Generating Process (see code table 4.3)
19 | 1 | Background Process
20 | 1 | Generating Process Identifier
21-22 | 2 | Hours After Data Cut-off
23 | 1 | Minutes After Data Cut-off
24 | 1 | Indicator of Unit of Time Range (see code table 4.4)
25- 28 | 4 | Forecast Time
29 | 1 | Type of First Fixed Surface (see code table 4.5)
30 | 1 | Scale Factor of First Fixed Surface
31-34 | 4 | Scaled Value of First Fixed Surface
35 | 1 | Type of Second Fixed Surface (see code table 4.5)
36 | 1 | Scale Factor of Second Fixed Surface
37-40 | 4 | Scaled Value of Second Fixed Surface
41 | 1 | Type of Ensemble Forecast (see code table 4.6)
42-45 | 4 | Perturbation Number
46-49 | 4 | Number of Forecasts in Ensemble

Notes:
* The input process identifier shall have the value of the "analysis or forecast process identifier" of the original GRIB message used as input of the post-processing.
* The input originating centre shall have the value of the "originating centre" of the original GRIB message used as input of the post-processing.

TEMPLATE 4.150, Average, accumulation, extreme values or other statistically processed values, at a horizontal level or in a horizontal layer in a continuous or non-continuous time interval for hazards
Octet | Number of octets | Description
-- | -- | --
10 | 1 | Parameter Category (see code table 4.1)
11 | 1 | Parameter Number (see code table 4.2)
12-13 | 2 | Hazard Profile (see Code Table 4.253)
14-15 | 2 | Input process Identifier (See Note 1)
16-17 | 2 | Input originating centre (see Common Code table C-11 and Note 2)
18 | 1 | Type of Generating Process (see code table 4.3)
19 | 1 | Background Process
20 | 1 | Generating Process Identifier
21-22 | 2 | Hours After Data Cut-off
23 | 1 | Minutes After Data Cut-off
24 | 1 | Indicator of Unit of Time Range (see code table 4.4)
25- 28 | 4 | Forecast Time
29 | 1 | Type of First Fixed Surface (see code table 4.5)
30 | 1 | Scale Factor of First Fixed Surface
31-34 | 4 | Scaled Value of First Fixed Surface
35 | 1 | Type of Second Fixed Surface (see code table 4.5)
36 | 1 | Scale Factor of Second Fixed Surface
37-40 | 4 | Scaled Value of Second Fixed Surface
41-42 | 2 | Year of end of overall time interval
43 | 1 | Month of end of overall time interval
44 | 1 | Day of end of overall time interval
45 | 1 | Hour of end of overall time interval
46 | 1 | Minute of end of overall time interval
47 | 1 | Second of end of overall time interval
48 | 1 | n - number of time range specifications describing the time intervals used to calculate the statistically processed field
49-52 | 4 | Total number of data values missing in statistical process
  |   | 53 - 64 Specification of the outermost (or only) time range over which statistical processing is done
53 | 1 | Statistical process used to calculate the processed field from the field at each time increment during the time range (see code table 4.10)
54 | 1 | Type of time increment between successive fields used in the statistical processing (see code table 4.11)
55 | 1 | Indicator of unit of time for time range over which statistical processing is done (see code table 4.4)
56-59 | 4 | Length of the time range over which statistical processing is done, in units defined by the previous octet
60 | 1 | Indicator of unit of time for the increment between the successive fields used (see code table 4.4)
61-64 | 4 | Time increment between successive fields, in units defined by the previous octet
  |   | 65 - nn These octets are included only if n > 1, where nn = 53+ 12 x n
65-76 | 12 | As octets 53 to 64, next innermost step of processing
77-nn | n/a | Additional time range specifications, included in accordance with the value of n. Contents as octets 53 to 64, repeated as necessary

Notes:
* The input process identifier shall have the value of the "analysis or forecast process identifier" of the original GRIB message used as input of the post-processing.
* The input originating centre shall have the value of the "originating centre" of the original GRIB message used as input of the post-processing.

TEMPLATE 4.151, Individual ensemble forecast, control and perturbed, at a horizontal level or in a horizontal layer, in a continuous or non-continuous interval, for hazards
Octet | Number of octets | Description
-- | -- | --
10 | 1 | Parameter Category (see code table 4.1)
11 | 1 | Parameter Number (see code table 4.2)
12-13 | 2 | Hazard Profile (see Code Table 4.253)
14-15 | 2 | Input process Identifier (See Note 1)
16-17 | 2 | Input originating centre (see Common Code table C-11 and Note 2)
18 | 1 | Type of Generating Process (see code table 4.3)
19 | 1 | Background Process
20 | 1 | Generating Process Identifier
21-22 | 2 | Hours After Data Cut-off
23 | 1 | Minutes After Data Cut-off
24 | 1 | Indicator of Unit of Time Range (see code table 4.4)
25- 28 | 4 | Forecast Time
29 | 1 | Type of First Fixed Surface (see code table 4.5)
30 | 1 | Scale Factor of First Fixed Surface
31-34 | 4 | Scaled Value of First Fixed Surface
35 | 1 | Type of Second Fixed Surface (see code table 4.5)
36 | 1 | Scale Factor of Second Fixed Surface
37-40 | 4 | Scaled Value of Second Fixed Surface
41 | 1 | Type of Ensemble Forecast (see code table 4.6)
42-45 | 4 | Perturbation Number
46-49 | 4 | Number of Forecasts in Ensemble
50-51 | 2 | Year of end of overall time interval
52 | 1 | Month of end of overall time interval
53 | 1 | Day of end of overall time interval
54 | 1 | Hour of end of overall time interval
55 | 1 | Minute of end of overall time interval
56 | 1 | Second of end of overall time interval
57 | 1 | n - number of time range specifications describing the time intervals used to calculate the statistically processed field
58-61 | 4 | Total number of data values missing in statistical process
  |   | 62 - 73 Specification of the outermost (or only) time range over which statistical processing is done
62 | 1 | Statistical process used to calculate the processed field from the field at each time increment during the time range (see code table 4.10)
63 | 1 | Type of time increment between successive fields used in the statistical processing (see code table 4.11)
64 | 1 | Indicator of unit of time for time range over which statistical processing is done (see code table 4.4)
65-68 | 4 | Length of the time range over which statistical processing is done, in units defined by the previous octet
69 | 1 | Indicator of unit of time for the increment between the successive fields used (see code table 4.4)
70-73 | 4 | Time increment between successive fields, in units defined by the previous octet
  |   | 74 - nn These octets are included only if n > 1, where nn = 62+ 12 x n
74-85 | 12 | As octets 62 to 73, next innermost step of processing
86-nn | n/a | Additional time range specifications, included in accordance with the value of n. Contents as octets 62 to 73, repeated as necessary

Notes:
* The input process identifier shall have the value of the "analysis or forecast process identifier" of the original GRIB message used as input of the post-processing.
* The input originating centre shall have the value of the "originating centre" of the original GRIB message used as input of the post-processing.

ADD new Code Table 4.253, Hazard profiles
Code | Description
-- | --
0 | Reserved
1 | Downburst
2 | Lightning (Electrical Storm)
3 | Thunderstorm
4 | Coastal Flood
5 | Estuarine (Coastal) Flood
6 | Flash Flood
7 | Fluvial (Riverine) Flood
8 | Groundwater Flood
9 | Ice-Jam Flood Including Debris
10 | Ponding (Drainage) Flood
11 | Snowmelt Flood
12 | Surface Water Flooding
13 | Glacial Lake Outburst Flood
14 | Black Carbon (Brown Clouds)
15 | Dust storm or Sandstorm
16 | Fog
17 | Haze
18 | Polluted Air
19 | Sand haze
20 | Smoke
21 | Ocean Acidification
22 | Rogue Wave
23 | Sea Water Intrusion
24 | Sea Ice (Ice Bergs)
25 | Ice Flow
26 | Seiche
27 | Storm Surge
28 | Storm Tides
29 | Tsunami
30 | Depression or Cyclone (Low Pressure Area) (Pressure-Related)
31 | Extra-tropical Cyclone (Pressure-Related)
32 | Sub-Tropical Cyclone (Pressure-Related)
33 | Acid Rain
34 | Blizzard
35 | Drought
36 | Hail
37 | Ice Storm
38 | Snow
39 | Snow Storm
40 | Cold Wave
41 | Dzud
42 | Freeze
43 | Frost (Hoar Frost)
44 | Freezing Rain (Supercooled Rain)
45 | Glaze
46 | Ground Frost
47 | Heatwave
48 | Icing (Including Ice)
49 | Thaw
50 | Avalanche
51 | Mud Flow
52 | Rock slide
53 | Derecho
54 | Gale (Strong Gale)
55 | Squall
56 | Subtropical Storm
57 | Tropical Cyclone (Cyclonic Wind, Rain [Storm] Surge) (Wind-Related)
58 | Tropical Storm (Wind-Related)
59 | Tornado
60 | Wind
61-100 | Reserved for meteorological and hydrological hazard indices
101 | Household Air Pollution
102 | Air Pollution (Point Source)
103 | Ambient (Outdoor) Air Pollution
104 | Land Degradation
105 | Soil Degradation
106 | Runoff / Nonpoint Source Pollution
107 | Salinity
108 | Biodiversity Loss
109 | Deforestation
110 | Forest Declines and Diebacks
111 | Forest Disturbances
112 | Forest Invasive Species
113 | Wildfires
114 | Desertification
115 | Loss of Mangroves
116 | Wetland Loss/Degradation
117 | Coral Bleaching
118 | Compressive Soils
119 | Soil Erosion
120 | Coastal Erosion and Shoreline Change
121 | Permafrost Loss
122 | Sand Mining
123 | Sea Level Rise
124 | Eutrophication
125-200 | Reserved for environmental hazard indices
201-32767 | Reserved for additional official hazard indices
32768-65534 | Reserved for local use
65535 | Missing

ADD new Code Table 4.254, Hazard index
Code | Description
-- | --
0 | Undefined
1-191 | Reserved (see Note 1)
192-254 | Reserved for local use
255 | Missing

Notes:
* The hazard index can be locally defined by the centre.

### Requestor(s)

Sebastien Villaume (ECMWF)
Matthew Griffith (ECMWF)
Robert Osinski (ECMWF)

### Stakeholder(s)

ECMWF
Destination Earth

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.0 (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.2.20.X (update)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.253 (create)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB code table 4.254 (create)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.148 (create)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.149 (create)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.150 (create)
Manual on Codes (WMO-No. 306), Volume I.2, GRIB Template 4.151 (create)

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/et-data/wiki/2024.12.03.et.data notes: 
Matthew introduced the alternate proposal, using the same idea of #285 but adding new templates instead to encode the octet; values are from a UN WMO hazard profile document;
