### ISSUE TITLE
Code/Flag table 3.1: GRIB Mercator grid types

### ISSUE THREAD

**Issue by shahramn** [wmo-im/GRIB2#33]
# **Branch**

[https://github.com/wmo-im/GRIB2/tree/issue33](https://github.com/wmo-im/GRIB2/tree/issue33)

# Discussion

I noticed that the Code/Flag table 3.1 has ONE entry for Mercator

```
Code table 3.1 – Grid definition template number
10 Mercator
11-12 Reserved
```

But the Templates document has TWO entries:

```
Grid definition template 3.10 – Mercator
Grid definition template 3.12 – transverse Mercator
```

Why is there a template for 3.12 but it's not in the table?

# Proposal

Add Transverse Mercator to Code Table 3.1

<table><tbody><tr><td>Grid definition template number</td><td>&nbsp;</td><td>12</td><td>&nbsp;</td><td>Transverse Mercator</td></tr></tbody></table>

**Comment by sebvi** [comment]
We have indeed a Grid Definition Template 3.12 that is not reference in Code table 3.1, we need to add it. Can we create a branch @amilan17 ? Thanks

**Comment by amilan17** [comment]
https://github.com/wmo-im/GRIB2/tree/issue-33

**Comment by amilan17** [comment]
@amilan17 update branch

**Comment by chenxiaoxia2019** [comment]
@amilan17 The branch has been updated. One minor question for "transverse", shall we use "transverse Mercator" or "Transverse Mercator"? Currently, template 3.12 is using "transverse Mercator". But, I notice that in Code table 3.1, all the first words are capitalized.

**Comment by chenxiaoxia2019** [comment]
@amilan17  As agreed, we use "Transverse Mercator" in both the Code table 3.1 and the template 3.12. The branch has been updated accordingly.
> @amilan17 The branch has been updated. One minor question for "transverse", shall we use "transverse Mercator" or "Transverse Mercator"? Currently, template 3.12 is using "transverse Mercator". But, I notice that in Code table 3.1, all the first words are capitalized.

**Comment by chenxiaoxia2019** [comment]
@amilan17 @shahramn @jitsukoh The branch has been updated.

**Comment by jitsukoh** [comment]
@amilan17 @shahramn @chenxiaoxia2019 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
