### ISSUE TITLE
Comments received on DRAFT AMENDMENTS TO THE  MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE             

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/GRIB2#51]
# Summary and purpose
_DRAFT AMENDMENTS TO THE MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE_    has been sent out on 28 July, 2020.     
 
The focal points for codes and data representation matters are invited to review and comment by 29 September, 2020.    

There are 13 proposals in _Part B - Binary Codes: FM 92 GRIB_, from No.1 to No.13.

# Action proposed
Comments received will be recorded here.

# Documents
[FT-2020-2-Vol I.2.pdf](https://github.com/wmo-im/GRIB2/files/4993592/FT-2020-2-Vol.I.2.pdf)

**Comment by sebvi** [comment]
Is it possible to have a pre-operational version of this as a csv/xml  for testing purpose?

**Comment by amilan17** [comment]
Amendments were approved by FT-2020-2
