### ISSUE TITLE
add Potential evapotranspiration rate in Code Table 4.2, product discipline 2, category 0

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#54]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue-54

# Summary and purpose
This document propose to add a new entry for "potential evapotranspiration rate" in Code table 4.2 discipline 2, category 0.

# Action proposed
The team is requested to approve the content of this proposal for inclusion with the next update of the WMO Manual on Codes.

# Discussions
The Copernicus Climate Change Service (C3S) project ULYSSE (mULti-model hYdrological SeaSonal prEdictionS system)  provides  a “seamless” multi-model hydrological seasonal prediction system using four state- of-the-art hydrological models (HMs) at a spatial resolution of 0.1 deg globally. Four HMs (JULES, HTESSEL, mHM, PCR-GLOBWB) will deliver forecasts of surface temperature, total precipitation, evapotranspiration, potential evapotranspiration, snow water equivalent, snowmelt, total volumetric soil moisture, total runoff and discharge. All these parameters, except potential evapotranspiration are well defined in GRIB2. We would like to propose to include in Code table 4.2 discipline 2, category 0

PET ("potential evapotranspiration rate" also called "reference crop evapotranspiration" ET~o~) is defined as "the amount of water that would be evaporated and transpired by a short green crop (grass) of uniform height, completely shading the ground, if there were sufficient water available".  If the "actual evapotranspiration rate" (ET) is considered "the net result of atmospheric demand for moisture from a surface and the ability of the surface to supply moisture, then PET is a measure of the demand side." There are numerous methods to estimate PET, e.g.,  the Thornthwaite equation (1948),  Penman-Monteith equation (1965),  Priestley–Taylor (1972), Hargreaves and Samani (1982). Since the PET is required for the estimation of irrigation rates worldwide, the FAO provided a standardisation procedure called the  FAO Penman-Monteith equation (http://www.fao.org/3/x0490e/x0490e06.htm#equation ), which is commonly used in hydrological modelling and irrigation scheduling.

# Detailed proposal
add an entry in Code table 4.2, discipline 2, category 0
Octet Meaning Units
40 Potential evapotranspiration rate kg m-2 s-1

**Comment by amilan17** [comment]
https://github.com/wmo-im/GRIB2/tree/issue-54

**Comment by sebvi** [comment]
branch updated
