### ISSUE TITLE
Question: use of Product Definition Templates and Code Table 4.2 for Aerosols vs chemical constituents.

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#63]
# Proposal
Add note to Code Table 4.2
Product Discipline 0 - Meteorological products, parameter category 13: aerosols. 
"This category is no longer populated, please use "Product discipline 0 – Meteorological products, parameter category 20: atmospheric chemical constituents."

# Discussion
In section 4, we have sets of Product Definition Templates (PDTs) for aerosol and for chemical constituents. 

The templates for **aerosols** always refer to an "aerosol type" which is coded in **Code Table 4.233** which in turn is only a proxy for the **Common Code Table 14**.
The templates for **chemical constituent type** always refer to an "atmospheric chemical constituent type" which is coded in **Code Table 2.230** which is in turn is also a proxy for the same **Common Code Table 14**.
So, in principle, it is the same Common Code Table used for all aerosols and chemical constituents.

To specify the type of physical/chemical property, there are 2 sub-tables in the Code Table 4.2, namely the sub-table **"discipline 0 category 13 - Aerosols"** and the sub-table **"discipline 0, category 20 - Atmospheric Chemical Constituents"**.
However, it seems that the first sub-table **has never been used/populated** apart from the first initial entry created in it, and one can see that many entries in the second sub-tables were intended to use with aerosols!

# Questions

- Was it initially intended to use the aerosols PDT with code table 4.2 discipline 0, category 13 only and the chemical PDT with code table 4.2 discipline 0, category 20 only?
- if this is the case and the team would like to follow this, should we deprecate many entries in code table 4.2 discipline 0 category 20 and moved them into code table 4.2 discipline 0, category 13?
- or Should we decide to recommend to stop using/adding entries in code table 4.2 discipline 0 category 13 and only use the other table for both aerosols and chemical constituents.

I am personally in favor of the later option. In GRIB3, we will use the same template component for both the aerosols and the chemical constituents, with one extra template component for aerosols. This makes sense because the aerosol templates are simply a copy of the chemical constituents templates with extra keys to specify a particle size range.

**Comment by amilan17** [comment]
@wmo-im/tt-tdcf -- please see Sebastien's questions and contribute to discussion in issues.

**Comment by sebvi** [comment]
@wmo-im/tt-tdcf  WE really would like to have a definitive answer on this. Should I organize a separate meeting with those interested so that we can reach an agreement/consensus?

**Comment by jbathegit** [comment]
Hello @sebvi and @amilan17.   My vote would also be for the last option.  I'm not sure of the original intent, but at this point I see no practical reason to deprecate and move a bunch of entries from category 20 to 13.  Furthermore, having everything in one table (category 20) makes the most sense to me going forward, especially given your point about how the same template components are already planned to be used in GRIB3 for both aerosols and chemical constituents.

**Comment by etoyoda** [comment]
Dear Sebastian,

Chair Jitsuko called me to respond.

From the conclusion I'm in line with your later option. 

I'm relatively old in this group, but even I don't know the actual debate to separate (only the name of) the code tables 4.230 and 4.233. When I came to the group the situation is basically the same: we had PDTs for chemical constituents (PDT 4.40-43) and those for aerosols (PDT 4.44-47) and both shared the same CCT-14 for identification of particles or molecules.  And the expert team was discussing to create new Aerosol template 4.48.

My understanding is the choice of the template depends on the metadata we have: please note PDT's 4.44-48 can describe the size of particles and PDT's 4.40-43 cannot. We could use chemical PDT if we don't have information on particle size.
(see https://docs.google.com/spreadsheets/d/1nBFJTUt3Qld3fXwtS-W_yoPDYLOeMYiToicZAkdDiFw/edit?usp=sharing if some of you don't know the templates)

The category 13 has long been puzzle for me. The units of parameter zero is code table 4.205. That means the data section describes different type of atmospheric constituents depending on the grid.  I cannot imagine real use case to have data like "dust at Beijing, sulphate at Tokyo, volcanic ash at Manila".

I have no problem to stop populating the category 13, and I can live with calling it discouraged or deprecated, but we have tradition to be really careful to remove something in the code form.

Best Regards,
Eizi TOYODA, Japan Meteorological Agency

**Comment by sebvi** [comment]
Dear @jbathegit  and @etoyoda ,

Thank you both for your comments. 

It seems to me that we all agree and that we should stop using and updating discipline 0, category 13 within the Code Table 4.2

@jitsukoh : How should we proceed from here to "retire" category 13 and use only category 20?

**Comment by jitsukoh** [comment]
@sebvi I agree with the way forward. Procedure-wise, we can add a note to category 13 saying that this category has stopped being populated in the PDF version. I am not sure about the existing entry (0 Aerosol type). If we "deprecate" it, we need to suggest an alternative way, like "use xxx instead." What do you think?
@amilan17 is there a way to add a note to whole category 13 in CSV on github?

**Comment by amilan17** [comment]
@jitsukoh -- we can only reference notes for particular codes within a table. However, we will be able to manage this in the new (upcoming) notes.csv file, which will identify the scope of the note (code, table...).

**Comment by amilan17** [comment]
@sebvi -- add a sentence for the note that should be added to the manual

**Comment by amilan17** [comment]
@sebvi @jitsukoh please review the note. In the manual, I will be between the title and the table. 

Note: This category is deprecated, please use "Product discipline 0 – Meteorological products, parameter category 20: atmospheric chemical constituents" instead.

**Comment by sebvi** [comment]
I am not sure about the note. Essentially the decision we are taking to stop using the category 13 and only add new parameter in category 20 is mainly for us in the Team. Users don't need to know, it is more a reminder for us. 

On the note itself, I don't think we can use the word "deprecated". The unique entry 0 defined in category 13 is still perfectly valid to use and we don't provide an alternative encoding in category 20. Usually when we deprecate a parameter/table/template, it is because something is wrong and we usually point to a corrected alternative.

So the question is: Should we re-create "aerosol type" in category 20 and point to it as the alternative of category 13, entry 0? Note that at the moment, entry 0 is simply a bitmap/mask in disguise: 0=no aerosol, 1=some aerosol (see code table 4.205).

@wmo-im/tt-tdcf : please comment :)

**Comment by jbathegit** [comment]
I agree with @sebvi.  I think this is more of an agreement among ourselves that we will no longer populate Category 13, but I agree that we can't deprecate it if there's no alternative to the existing entry 0.  If we wanted to copy entry 0 into Category 20 and point users to that, then that would be an option, though I believe an unnecessary one because, as others have already pointed out, this is already set to be addressed within GRIB3.

**Comment by amilan17** [comment]
ok. So no need to put a note in the manual.

**Comment by jitsukoh** [comment]
@sebvi @jbathegit @amilan17 I agree with the word "deprecated." Existing codes should not be deprecated without alternatives. On the other hand, I think a note to indicate that this category will no longer be populated would be helpful, because not all users are our team members and also current members will not be there forever...
My proposal is "Note: This category is no longer populated, please use "Product discipline 0 – Meteorological products, parameter category 20: atmospheric chemical constituents" instead." Any suggestion would be appreciated.

**Comment by jbathegit** [comment]
Thanks @jitsukoh - adding your suggested note seems like a good and reasonable compromise approach, and I would support that.

Cc'ing @sebvi and @amilan17 in case they have any additional comments or thoughts.
