### ISSUE TITLE
Data representation template 5.42 title incorrect

### ISSUE THREAD

**Issue by shahramn** [wmo-im/GRIB2#64]
Regarding the Data representation template 5.42:
"Grid point and spectral data - CCSDS recommended lossless compression"

The title of this scheme mentions "spectral data", which is confusing me as it does not have the right keys for representing spectral packing. Isn't CCSDS just like JPEG and PNG? if so then it would only be for **GRID-POINT data** and not spectral.

Its Note (1) says:

> "The intent of this template is to scale the grid point data to obtain the desired precision, if appropriate, and then subtract the reference value from the scaled field, as is done using data representation template 5.0..."

So it affirms my suspicions: It is for GRID-POINT data. Later the note mentions data representation template 5.0 which is again for grid-point data (Grid point data-simple packing)

**Comment by sebvi** [comment]
My understanding is that this can be treated as an editorial change.

**Comment by efucile** [comment]
I agree that this is an editorial change.

**Comment by sebvi** [comment]
@wmo-im/tt-tdcf  should we include this in FT-2021-1 ?

**Comment by tomkralidis** [comment]
+1 from me.

**Comment by jitsukoh** [comment]
@sebvi @tomkralidis thank you very much for the reminder.
@amilan17 I would suggest that we include this in FT2021-1 as an editorial change.

**Comment by amilan17** [comment]
@shahramn 

I removed 'and spectral data' from the title. Can you confirm that this in alignment with the decision? 

a711c82

**Comment by shahramn** [comment]
It should start with "Grid point data - ". You have omitted the "data"
So line one should be:
`Grid point data - CCSDS recommended lossless compression,12-15,Reference value (R) (IEEE 32-bit floating-point value),,Operational`

**Comment by sebvi** [comment]
@amilan17 : This issue has the FT2021-1 milestone but is not tagged with the branch FT-2021. Will it be part of the next release?

**Comment by amilan17** [comment]
It is in this FT2021-1 release. :-)

**Comment by shahramn** [comment]
In the latest draft version (release candidate) I still see instances of the old title

```
% grep -r 'spec.*CCSDS' GRIB2-27RC
GRIB2-27RC/GRIB2_CodeFlag_5_0_CodeTable_en.csv:Data representation template number,,42,,Grid point and spectral data - CCSDS recommended lossless compression,,,Operational
GRIB2-27RC/GRIB2_Template_7_42_DataTemplate_en.csv:Grid point and spectral data - CCSDS recommended lossless compression,6-nn,CCSDS recommended standard for lossless data compression code stream,,Operational
GRIB2-27RC/csv/CodeFlag.txt:Code table 5.0 - Data representation template number,,42,,Grid point and spectral data - CCSDS recommended lossless compression,,,Operational
GRIB2-27RC/csv/Template.txt:Data template 7.42 - Grid point and spectral data - CCSDS recommended lossless compression,6-nn,CCSDS recommended standard for lossless data compression code stream,,Operational
GRIB2-27RC/csv/CodeFlag.txt.tsv:Code table 5.0 - Data representation template number            42              Grid point and spectral data - CCSDS recommended lossless compression                     Operational
GRIB2-27RC/csv/27.draft/5.0.table:42 42 Grid point and spectral data - CCSDS recommended lossless compression 
GRIB2-27RC/xml/CodeFlag.xml:            <MeaningParameterDescription_en>Grid point and spectral data - CCSDS recommended lossless compression</MeaningParameterDescription_en>
GRIB2-27RC/xml/Template.xml:            <Title_en>Data template 7.42 - Grid point and spectral data - CCSDS recommended lossless compression</Title_en>
```

**Comment by efucile** [comment]
@shahramn thanks
we'll fix this in the final release

**Comment by amilan17** [comment]
@sebvi  - I updated the GRIB2\_Template\_7\_42\_DataTemplate\_en.csv and GRIB2\_CodeFlag\_5\_0\_CodeTable\_en.csv in branch Issue64 and requested you to review the pull request.
