### ISSUE TITLE
GRIB2_CodeFlag_4_2_CodeTable_en.csv: unit for code 19

### ISSUE THREAD

**Issue by shahramn** [wmo-im/GRIB2#74]
# Branch

https://github.com/wmo-im/GRIB2/tree/issue74

# Initial Statement

In this table, there is a Code Table entry 19 which reads:  
19,,Precipitation type,,(4.201),Operational

This should be changed to:  
19,,Precipitation type,,(Code table 4.201),Operational

Just like the other table entry 123 (Dominant precipitation type)

**Comment by amilan17** [comment]
Branch is updated and manual it is already published correctly in the manual.
