### ISSUE TITLE
Validate Machine Readable Codes - v27 Release Candidate

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#75]
# RC
https://github.com/wmo-im/GRIB2/releases/tag/v27RC.4

# Summary and purpose
To ensure that the machine-readable codes v27RC are valid and ready for testing during the comment period. 

# Action proposed
1.   [x] Update script to ensure consistent output order
1.   [x] identify key individuals to test
1.   [x] Confirm file validation

# Discussions

# **Machine-Readable Files**

*   [x] CodeFlag.txt
*   [x] Template.txt
*   [x] CodeFlag.xml
*   [x] Template.xml

**Comment by SimonElliottEUM** [comment]
Code/Flag looks strange.

XML is NOK because of None types being used. We've had this before. Must be analysed by inspection of XML file to figure out what's going on, probably omitted tags.
XML file looks like it contains 94 elements total, CSV has 151. What gives?
Regarding XML: The elements in question do this:

<GRIB2_CodeFlag_en>
<Title_en>Code table 4.225 - Weather</Title_en>
<CodeFlag/>
<MeaningParameterDescription_en>(see FM 94 BUFR/FM 95 CREX Code table 0 20 003 - Present weather)</ MeaningParameterDescription_en>
<Status>Operational</Status>
</GRIB2_CodeFlag_en>

The "naked" <CodeFlag/> tag is what's causing the problems - this was also the case in the last one. Vocabulary Manager expects this to be expressed as an empty double-tag, i.e. <CodeFlag></CodeFlag>

**Comment by SimonElliottEUM** [comment]
XML file looks like it contains 94 elements total, CSV has 151. Please explain

**Comment by amilan17** [comment]
@erget @SimonElliottEUM -- 

<table><tbody><tr><td>The CodeFlag XML file looks like it contains 94 elements total, CSV has 151.</td></tr></tbody></table>

I'm unable to find a count of 151 "elements". 

The source code has 94 CodeFlag tables represented in CSV files. 

When I evaluate the machine-readable codes, I see that the TXT file has 2,248 lines (including header) and the XML file has 2,247 \<GRIB2\_CodeFlag\_en> nodes. In a spreadsheet analysis I see that both have 94 CodeFlag tables.

**Comment by erget** [comment]
@amilan17 [here are the imported GRIB2 Code/Flag table entries](https://vocabulary-manager.eumetsat.int/vocabularies/GRIB/WMO/100/TABLE_CODE_FLAG). I got them out of the CSV.

I've inspected all of these manually and it looks legitimate to me - all entries are code/flag tables, there are 151 of them, and they are all unique as far as I can tell (I was checking by reading through, don't have a computer programme for it). My guess is that the XML file is missing entries?

If you get a chance, please have a look at the linked site above and let me know if I'm missing something.

**Comment by amilan17** [comment]
@erget - the difference is how the EUMETSAT Vocabulary Manager handles Code table 4.2.  

Code table 4.2 - Parameter number by product discipline and parameter category == is one table in the source CSV, XML and TXT on GitHub. e.g. 

<table><tbody><tr><td><strong>Title_en</strong></td><td><strong>SubTitle_en</strong></td><td><strong>CodeFlag</strong></td><td><strong>Value</strong></td><td><strong>MeaningParameterDescription_en</strong></td></tr><tr><td>Code table 4.2 - Parameter number by product discipline and parameter category</td><td>Product discipline 0 - Meteorological products, parameter category 0: temperature</td><td>0</td><td>&nbsp;</td><td>Temperature</td></tr><tr><td>Code table 4.2 - Parameter number by product discipline and parameter category</td><td>Product discipline 0 - Meteorological products, parameter category 0: temperature</td><td>1</td><td>&nbsp;</td><td>Virtual temperature</td></tr></tbody></table>

However, the vocabulary manager lumps all the values into one entry. Thus multiplying the number of entries. 

<table><tbody><tr><td><strong>_id</strong></td><td><strong>name</strong></td><td><strong>values/0/codeentry</strong></td><td><strong>values/0/codefigure</strong></td></tr><tr><td>4.2.0.0</td><td>Code table 4.2 - Parameter number by product discipline and parameter category # Product discipline 0 - Meteorological products, parameter category 0: temperature</td><td>Temperature</td><td>0</td></tr><tr><td>4.2.0.1</td><td>Code table 4.2 - Parameter number by product discipline and parameter category # Product discipline 0 - Meteorological products, parameter category 1: moisture</td><td>Specific humidity</td><td>0</td></tr></tbody></table>

**Comment by amilan17** [comment]
@erget - on a different note, you said "I got them out of the CSV". Is the vocabulary manager importing the _source_ \*.csv files or the  \*.txt files in the csv folder?

**Comment by erget** [comment]
@amilan17 good eye, that's the rub. I imported the 2 files in the CSV folder: `CodeFlag.txt` and `Template.txt`.

**Comment by amilan17** [comment]
validation complete
