### ISSUE TITLE
Code table 4.2: Discipline 4, category 2 table: code entry 8

### ISSUE THREAD

**Issue by shahramn** [wmo-im/GRIB2#79]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue79

# Initial Proposal
The entry 8 in Code Table 4.2.4.2 looks truncated:
```
0 Particle number density m-3
1 Electron density m-3
2 Proton density m-3
3 Ion density m-3
4 Vertical total electron content TECU
5 HF absorption frequency Hz
6 HF absorption dB
7 Spread F m
8 hâ m
9 Critical frequency Hz
10 Maximal usable frequency (MUF) Hz
11 Peak height (hm) m
12 Peak density (Nm) m-3
13 Equivalent slab thickness (tau) km
```
There are several non-ascii characters in there.
Our WMO rep Sebastien Villaume checked with Jeff Ator and we believe it should be:
`h'F`
(h prime F)

Can we please change this in all places it is mentioned e.g.
csv/CodeFlag.txt
GRIB2_CodeFlag_4_2_CodeTable_en.csv
xml/CodeFlag.xml

Thanks

**Comment by shahramn** [comment]
I hope this will be included in the May release

**Comment by amilan17** [comment]
Unfortunately, this will have to be included in the November release, because the amendments for May are already out for review.

**Comment by chenxiaoxia2019** [comment]
@amilan17 @shahramn The branch with the correct "h'F" has been updated.

**Comment by shahramn** [comment]
> @amilan17 @shahramn The branch with the correct "h'F" has been updated.

That's excellent. Many thanks :+1:

**Comment by jitsukoh** [comment]
I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
Thank you @shahramn for spotting this and @amilan17 for the branch updating!
