### ISSUE TITLE
Code Table 4.2 and new code table: add code table entry for character of precipitation

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/GRIB2#81]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue81

# Summary and purpose
This document proposes a new GRIB2 Code Table 4.2 parameter as well as a new table (4.249).

# Action proposed
The @wmo-im/tt-tdcf team is requested to approve the content of this proposal for inclusion with the next update of the WMO Manual on Codes.

# Discussions
The tables contain a proposed addition to Table 4.2 as well as a new Table 4.248 within the GRIB2 section of the Manual on Codes. These are necessary to reflect new post-processing diagnostics and Nowcasting forecasts being implemented at the Meteorological Service of Canada.  The additions further qualify the character of precipitation to reflect how information is transmitted to users in the context of a fully automated forecast.  It is hoped that they are also sufficient for use by other Centers.

# Detailed proposal
### Addition to 4.2

| Parameter                                     | Product Discipline | Parameter Category | Parameter number | Units |
|-----------------------------------------------|--------------------|--------------------|------------------|-------|
| Character of precipitation                    | 0| 1 (moisture)         | 147|      (Code table 4.249)|

### New code table 4.249 (Character of precipitation)

| Title_en  | SubTitle_en  | CodeFlag | Value | MeaningParameterDescription_en  | Note_en  | UnitComments_en  | Status |
|-----------|--------------|----------|-------|---------------------------------|----------|------------------|--------|
|Character of precipitation ||0||None|||Operational|
|Character of precipitation ||1||Showers|||Operational|
|Character of precipitation ||2||Intermittent|||Operational|
|Character of precipitation ||3||Continuous|||Operational|

**Comment by sebvi** [comment]
I like and support this proposal. I only have 2 comments:

- When we create a parameters that is essentially a bitmap and refers to a table to decode the meaning of the integers we usually have "code table 4.XXX" in the units column so I would recommend to do this for this one (although I am not a huge fan of this practice!).
- In GRIB3, I hope that all these parameters that are essential quality/property flags would go as "overlays" in the newly created overlay section :)

**Comment by tomkralidis** [comment]
Merci @sebvi.  Proposal updated :)

**Comment by sebvi** [comment]
looks good to me, I support this proposal

**Comment by tomkralidis** [comment]
Update (2021-05-18):
- updated branch https://github.com/wmo-im/GRIB2/tree/issue81
- bumped code flag and code table entry numbers accordingly given they were taken at the time

**Comment by jitsukoh** [comment]
@tomkralidis @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
