### ISSUE TITLE
Code Table 4.2: add new codes for thermal stress indicators

### ISSUE THREAD

**Issue by tomkralidis** [wmo-im/GRIB2#82]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue82

# Summary and purpose
This document proposes a new GRIB2 Code Table 4.2 parameter.

# Action proposed
The @wmo-im/tt-tdcf team is requested to approve the content of this proposal for inclusion with the next update of the WMO Manual on Codes.

# Discussions
Biometeorological indices are used to measure the level of discomfort of humans due to several environmental conditions. Three of them, The Heat index, the apparent temperature, and the wind chill index are already part of the grib2 code Table 4.2, product discipline 0. Two other biometeorological indices, the Universal Thermal Climate Index (UTCI) and the Mean radiant temperature (MRT) have recently been added to the grib2 Table 4.2, product discipline 20.  This new family of indices now include in one value the effect of temperature, humidity, wind speed, and short and longwave radiation fluxes on the outdoor human body.
The Wet-bulb Globe Temperature (WBGT) is proposed to be added to the Grib2 table 4.2, product discipline 20.  WBGT is another integrated index reported among more than 10 biometeorological indices (including UTCI and MRT) presented in the document from WMO/WHO “Heatwaves and health: guidance on warning-system development” (WMO/WHO, 2015[1]). Due to climate change, more actions are being taken towards the development of Heat-Health Warning Systems (HHWS). The report mentions that “The choice of method for assessing heat stress will depend on the resources available to HHWS developers”. This document illustrates the benefit of retrieving different variables out of the governmental meteorological agencies.
WBGT is part of the international certification (ISO, 1989[2]). It is largely used in many sectors for which physical activity is considered, such as occupational health, sport federations, and defense organizations. At the early stage, WBGT was measured on-site.

It is relevant to add WBGT in the list of reference variables because this variable is now being forecasted in numerical weather and climate systems. For example, WBGT is part of the Canadian national short-range forecasts since July 2019. It is available at the surface for each grid point and over any type of surface, land, water, and urban landscapes [3]. Another example is the experimental maps of WBGT produced at NCEP [4]. 

### References
- WMO/WHO, 2015: Heatwaves and health: guidance on warning-system development G.R. McGregor, P. Bessemoulin, lead editor, and K. Ebi and B. Menne, editors.
- ISO 7243, 1989. Hot Environments – Estimation of the Heat Stress on Working Man, Based on the WBGT-index (Wet-bulb Globe Temperature). International Organization for Standardization (ISO), Geneva.
- Leroyer, S., Bélair, S., Spacek, L., Gultepe, I., 2018. Modelling of radiation-based thermal stress indicators for urban numerical weather prediction, Urban Climate, 25: 64-81. https://doi.org/10.1016/j.uclim.2018.05.003
- [National Weather Service - Graphical Forecast (noaa.gov)](https://digital.mdl.nws.noaa.gov/?zoom=4&lat=37&lon=-96.5&layers=F000BTTTFTT&region=0&element=8&mxmz=false&barbs=false&subl=TFFFFF&units=english&wunits=nautical&coords=latlon&tunits=localt)

# Detailed proposal
### Addition to 4.2

| Parameter                                     | Product Discipline | Parameter Category | Parameter number | Units |
|-----------------------------------------------|--------------------|--------------------|------------------|-------|
| Wet-bulb globe temperature                    | 20| 0: health indicators| 2| K     |

### Notes (for PDF)

Higher values indicate that heat stress is important. Interpretation of values can vary among organizations and use. See example in the ISO certification (ISO 7243 1989, 2017, and Parsons 2013).

### Additional Notes

Higher values indicate that heat stress is important. Interpretation of values can vary among organizations. For example the American Conference of Government Industrial Hygiene suggests that the thresholds depend on the work hardness. In the ISO certification, thresholds are as follows (in oC):
```
WBGT > 32 : Very High Heat Stress
 28 < WBGT < 32 : High Heat Stress
 23 < WBGT < 28 : Moderate Heat Stress 
WBGT < 23 : Low Heat Stress
```

**Comment by sebvi** [comment]
Dear @tomkralidis , UTCI and MRT already exist, they are in discipline 20, category 0.  :) 

The recently created discipline 20 is for all the "bio" related stuff :)

**Comment by tomkralidis** [comment]
Thanks @sebvi .  Proposal updated accordingly.

**Comment by sebvi** [comment]
looks good, I support this proposal

**Comment by tomkralidis** [comment]
Update via TT-TDCF 2021-04-20: we discussed whether notes should be added to the code entry to assist users who may not be familiar with WBGT.

We can add a note per below:

```
Higher values indicate that heat stress is important. Interpretation of values can vary among organizations and use. See example in the ISO certification (ISO 7243 1989, 2017, and Parsons 2013).
```

We could additionally add the references as specified in the proposal, but I'm not sure if/how that would fit into the CSVs.

**Comment by jitsukoh** [comment]
@amilan17 it seems that notes of GRIB2 parameters are attached in two ways (*, **, ***, ... and Note 1, Note 2, ... ) in PDF. In the case of this proposal, there is no need to include anything in CSV?

**Comment by tomkralidis** [comment]
Update (following 2021-05-18 meeting):

- updated branch https://github.com/wmo-im/GRIB2/tree/issue82
- updated "Additional Notes" in proposal (typo in ranges, thanks @jbathegit)

**Comment by amilan17** [comment]
@jitsukoh -- currently the notes are only organized for GRIB templates. For Code and Flag tables, the note needs to be clearly identified in the issue summary.

**Comment by jitsukoh** [comment]
@amilan17 thanks, my question is, in this proposal, do we need to have an indicator attached to the parameter Wet-bulb globe temperature in CSV, such as Wet-bulb globe temperature (*) or (Note 1) because this parameter has Note 1 (Higher values indicate that heat stress is important. Interpretation of values can vary among organizations and use. See example in the ISO certification (ISO 7243 1989, 2017, and Parsons 2013).) in PDF?

**Comment by amilan17** [comment]
@jitsukoh, yes the CSV should have an indicator in the notes\_en column for this note. I think in this case, it should be "see Note 1", however, these numbers may change when I compile all of the branches into FT.

**Comment by jitsukoh** [comment]
@amilan17 I don't think the entry in [this branch](https://github.com/wmo-im/GRIB2/compare/issue82) is not correct about how to deal with the note... Can you check it?

**Comment by amilan17** [comment]
@jitsukoh thanks, I fixed it for Tom.

**Comment by jitsukoh** [comment]
@amilan17 thank you! @tomkralidis I confirm that this proposal is finalized and the branch is updated. The issue is moved to the validated status.
