### ISSUE TITLE
Code Table 4.2: new entries requested by Norway

### ISSUE THREAD

**Issue by rmla-cz** [wmo-im/GRIB2#85]
### Branch

https://github.com/wmo-im/GRIB2/tree/issue85

### Stakeholder

*   MetNorway
*   ECMWF

### Summary and purpose

This document proposes new GRIB2 Code Table 4.2 parameters.

### Action proposed

The Team is requested to review the proposed new parameter and approve it for implementation.

### Discussions

The tables in this proposal contain parameters that will be of crucial importance for the Copernicus Arctic Regional Reanalysis project which has already started its production in 2020. These parameters have been widely used as GRIB1 local parameters in the HIRLAM numerical weather prediction community, and we thus believe they will be of high relevance outside the aforementioned reanalysis project.

### Final Proposal

| Parameter | Product Discipline | Parameter Category | Parameter number | Units |
| --- | --- | --- | --- | --- |
| Snow evaporation rate  (see Note 8) | 0 | 1 | 148 | kg m-2 s-1 |
| Surface roughness for heat (see Note 1) | 0 | 2 | 47 | m |
| Surface roughness for moisture (see Note 2) | 0 | 2 | 48 | m |

*   0-1, 62: Snow evaporation
    *   Note 8: It is recommended to use parameter 148.
*   0-1, 148: Snow evaporation rate
    *   Note 9: Snow evaporation is the accumulated amount of water that has evaporated from snow from within the snow covered area of a grid-box.
*   0-2, 47: Surface roughness for heat
    *   Note 1: Surface roughness for heat is a measure of the surface resistance to heat transfer.
*   0-2, 48: Surface roughness for moisture
    *   Note 2: Surface roughness for moisture is a measure of the surface resistance to moisture transfer.

### Initial proposal

Proposed new entry for Code Table 4.2:

| Parameter | Product Discipline | Parameter Category | Parameter number | Units |
| --- | --- | --- | --- | --- |
| Snow evaporation rate 1) | 0 | 1 | To be decided | kg m-2 s-1 |
| Surface roughness for heat 2) | 0 | 2 | To be decided | m |
| Surface roughness for moisture 3) | 0 | 2 | To be decided | m |

Comments:

1.  Snow evaporation is the accumulated amount of water that has evaporated from snow from the snow-covered area of a grid-box. **The existing parameter 62 Snow evaporation \[kg m-2\] should be deprecated**
2.  Surface roughness for heat is a measure of the surface resistance to heat transfer. It is a component of surface roughness.
3.  Surface roughness for moisture is a measure of the surface resistance to moisture transfer. It is a component of surface roughness.

**Comment by sebvi** [comment]
I have been in Contact with the proposer to help them formulate their request so I assigned the issue to myself to review/validate

**Comment by sebvi** [comment]
branch updated

**Comment by jitsukoh** [comment]
@sebvi @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.

**Comment by jitsukoh** [comment]
@sebvi sorry I should have asked you before I moved this issue to "Validated"; could you update **the original post** of this issue with the parameter numbers that you used to updated the branch? This small step would save time for the Secretariat when they compile all the proposals into one document...

**Comment by amilan17** [comment]
@sebvi These are my suggestions for notes in Code Table 4.2. If these notes are intended to be published and you agree with the suggestion, please update the branch and update the original proposal with final solution. (If you cannot update the original proposal, I will do this for you.)

*   0-1, 62: Snow evaporation
    *   Note 6: It is recommended to use parameter 147. 
*   0-1, 147: Snow evaporation rate 
    *   Note 7: Snow evaporation is the accumulated amount of water that has evaporated from snow ~~from~~ within the snow covered area of a grid-box.
*   0-2, 47: Surface roughness for heat
    *   Note 1: Surface roughness for heat is a measure of the surface resistance to heat transfer. It is a component of surface roughness.
*   0-2, 48: Surface roughness for moisture
    *   Note 2: Surface roughness for moisture is a measure of the surface resistance to moisture transfer. It is a component of surface roughness.

**Comment by sebvi** [comment]
@amilan17 I am happy with your suggestions
