### ISSUE TITLE
code table 4.2: cloud water mixing ratio (UK)

### ISSUE THREAD

**Issue by marqh** [wmo-im/GRIB2#88]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue88

# Summary and purpose
Request for a new code table 4.2 entry for  cloud water mixing ratio

# Action proposed
The Team is requested to review the proposed new parameter and approve it for implementation.

# Discussions
The UK Met Office generates data from its atmosphere models with a model diagnostic of  cloud water mixing ratio, which does not appear in the current GRIB parameter code tables.  The respesentation this quantity within WMO GRIB2 tables would assist in the sharing of this data. 
There are already two different cloud ice mixing ratio GRIB2 code table entries:
* 0-1-82
* 0-6-23

each with a unit of measure of kg/kg so cloud water mixing ratio appears a logical addition.

It is not clear to us what the difference between these two quantities is, and why there is a moisture category and a cloud category entry

# Finalized proposal
(edited by @jitsukoh June 17)
* Discipline: 0
* Category: 1
* Number: ~~148~~ 149
* Name:  Cloud water mixing ratio
* Units: kg/kg

**Comment by marqh** [comment]
@richardweedon 
@mgange659

**Comment by richardweedon** [comment]
Request the following - 
Product discipline 0 - Meteorological product  parameter category 1: moisture   27  Cloud Water mixing ratio  Kg/kg

**Comment by jitsukoh** [comment]
@richardweedon parameter number 27 is not vacant. You can find vacant numbers in the CSV table; please make sure numbers taken by #85 are not used.

**Comment by richardweedon** [comment]
Propose resetting the parameter number to 148 (Discipline 0 Category 1 Cloud Water Mixing Ratio Units kg / kg)

**Comment by jitsukoh** [comment]
@richardweedon @amilan17 I confirm that the proposal is finalized (I updated the original post) and the branch is updated. This is moved to the validated status.
