### ISSUE TITLE
code table 4.2: upward UV radiation (UK)

### ISSUE THREAD

**Issue by marqh** [wmo-im/GRIB2#90]
# Branch
https://github.com/wmo-im/GRIB2/tree/issue90

# Summary and purpose
Request for a new code table 4.2 entry for upward UV

# Action proposed
The Team is requested to review the proposed new parameter and approve it for implementation.

# Discussions
The UK Met Office generates data from its atmosphere models with a model diagnostic of upward UV, which does not appear in the current GRIB parameter code tables.  The respesentation this quantity within WMO GRIB2 tables would assist in the sharing of this data.

The GRIB2 tables already include a Downward UV radiation 0-4-12 so upward appears a sensible extension

# Finalized proposal
(edited by @jitsukoh June 17)
* Discipline: 0
* Category: 4
* Number: 15
* Name: Upward UV radiation emitted/reflected from the Earth surface
* Units: W m-2

**Comment by marqh** [comment]
@richardweedon 
@mgange659

**Comment by sebvi** [comment]
Do I understand correctly that this parameter is the UV radiation emitted/reflected by the surface and hence is not simply the downward UV radiation with a negative sign?

**Comment by amilan17** [comment]
pending further discussions

**Comment by marqh** [comment]
> 
> 
> Do I understand correctly that this parameter is the UV radiation emitted/reflected by the surface and hence is not simply the downward UV radiation with a negative sign?

Hello @sebvi @amilan17  

we can confirm that this is explicitly the UV radiation emitted/reflected from the Surface
I will update the proposal statement to include this phrasing, for clarity

thank you
mark

**Comment by richardweedon** [comment]
Request the following entries in Code Table 4.2 


"Product discipline 0 - Meteorological product  parameter category 4: short-wave radiation"    15      Upward UV radiation   W m-2 

"Product discipline 0 - Meteorological product  parameter category 4: short-wave radiation"    16 - 49 Reserved

**Comment by jitsukoh** [comment]
@richardweedon @marqh I think the parameter should  be named as "Upward UV radiation emitted/reflected from the Earth surface" to avoid misuse.

**Comment by marqh** [comment]
I agree with @jitsukoh this is a clear name that will avoid misuse.

I had previously updated the proposal to use the description:
`Upward UV radiation (Radiation Emitted/Reflected from the Earth Surface)`

I am happy to use this definition, with brackets, or to alter this to use the explicit text proposed by @jitsukoh, which is equally clear
`Upward UV radiation emitted/reflected from the Earth surface`

**Comment by jitsukoh** [comment]
@marqh @amilan17 I confirm that the proposal is finalized (I updated the original post to reflect this) and the branch is updated. This issue is moved to validated status.
