### ISSUE TITLE
code table 4.5: convective cloud level (UK)

### ISSUE THREAD

**Issue by marqh** [wmo-im/GRIB2#91]
# Branch

https://github.com/wmo-im/GRIB2/tree/issue91

# Summary and purpose

Request for a new code table 4.5 entries for convective cloud level

# Action proposed

The Team is requested to review the proposed new parameter and approve it for implementation.

# Discussions

The UK Met Office generates data from its atmosphere models on surfaces of convective cloud levels, which do not appear in the current GRIB parameter code tables. The representation these quantity within WMO GRIB2 tables would assist in the sharing of this data.

*   Name: Convective cloud layer bottom level
*   Name: Convective cloud layer top level
*   See attached document for details of the new entries -  
    [GRIB-CC-4.5.docx](https://github.com/wmo-im/GRIB2/files/6302937/GRIB-CC-4.5.docx)

# Final proposal
(edited by @jitsukoh July 2)
New entries in Code Table 4.5
**26: Convective cloud layer base
27: Convective cloud layer top**
**28** - 29 Reserved

**Comment by marqh** [comment]
@richardweedon 
@mgange659

**Comment by jitsukoh** [comment]
@amilan17 was this issue closed?

**Comment by amilan17** [comment]
apologies. Didn't mean to close the issue.

**Comment by richardweedon** [comment]
As discussed in attached document request the following - 26: Convective cloud layer bottom. 27: Convective Cloud Layer Top. Reserved entries re-numbered to '28 - 29 Reserved

**Comment by jitsukoh** [comment]
@richardweedon you don't need to close the issue and also you should be the assignee. 
Please update **the original post of this issue** with the final proposal, without using the word document, which saves a lot of work for the Secretariat.

**Comment by jitsukoh** [comment]
@richardweedon I updated the original post with the final proposal. Can you update the branch?

**Comment by jitsukoh** [comment]
@amilan17 I confirm that the proposal is finalized and the branch is updated. This issue is moved to validated status.

**Comment by jitsukoh** [comment]
@amilan17 @richardweedon I think both work w/ and wo/ but I leave this to Met Office' decision.

**Comment by marqh** [comment]
Hello All

having reviewed this proposal, the Met Office are happy to remove the term `level` from the definitions, this seems more consistent with the other entries 

we are also wary that the use of the term `bottom` is not consistent with other code table entries. the term `cloud base` has eight matches in the manual on codes, where as the term `cloud bottom` has zero matches

`cloud base` seems the preferred term for WMO.

So, we would like to propose that this is revised to define:

* 26, Convective cloud layer base
* 27, Convective cloud layer top

**Comment by jitsukoh** [comment]
@marqh I agree with your suggestion. I updated the original post with the proposal. Can you update the branch accordingly?

**Comment by amilan17** [comment]
@marq I will update the content in the FT branch.
