### ISSUE TITLE
Code table 4.2: publish product discipline 20 to manual

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#93]
# Summary and purpose

these were never published to the manual, but appear in GitHub v25 

<table><tbody><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>0</td><td>Health indicators</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>1</td><td>Epidemiology</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>2</td><td>Socioeconomic indicators</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>3-191</td><td>Reserved</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>192-254</td><td>Reserved for local use</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>255</td><td>Missing</td></tr></tbody></table>

**Comment by amilan17** [comment]
DIFF between v24 and v25: [https://github.com/wmo-im/GRIB2/compare/v24...v25#diff-6e02915ae3205f56509d9ba9ce36a0d26f69ac4fbd6c6e02a86ff3720dc062d6](https://github.com/wmo-im/GRIB2/compare/v24...v25#diff-6e02915ae3205f56509d9ba9ce36a0d26f69ac4fbd6c6e02a86ff3720dc062d6)

<table><tbody><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>0</td><td>Health indicators</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>1</td><td>Epidemiology</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>2</td><td>Socioeconomic indicators</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>3-191</td><td>Reserved</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>192-254</td><td>Reserved for local use</td></tr><tr><td>Product discipline 20 - Health and socioeconomic impact</td><td>255</td><td>Missing</td></tr></tbody></table>

**Comment by jitsukoh** [comment]
@amilan17 sorry I forgot the discussion in the meeting... This proposal was approved in the past but dropped from the publication of PDF manual, so it will be included in the next publication (no need to change github csv), is that right? In this case, can I move this to "validated" status?

**Comment by amilan17** [comment]
correct. no need to need to create and edit a branch for this.

**Comment by jitsukoh** [comment]
@amilan17 thanks, then I move this to validated status.
