### ISSUE TITLE
code table 4.2: new parameter "Solar induced chlorophyll fluorescence" for atmospheric composition modelling

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#95]
# Branch 
https://github.com/wmo-im/GRIB2/tree/issue95

# Summary and purpose
ECMWF is requesting a new parameter for its atmospheric composition modelling.

# Action proposed
The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
ECMWF is requesting a new parameter for its atmospheric composition modelling : solar induced chlorophyll fluorescence. The parameter will be reported/calculated at various wavelengths using product templates for satellite products.

# Detailed proposal

add in code table 4.2 discipline 4, category 8
| Code | Meaning | Units |
|--|--|--|
| 8 | Solar induced Chlorophyll Fluorescence | W m-2 sr-1 m-1 |

**Comment by sebvi** [comment]
updated to remove the scaling factor

**Comment by sebvi** [comment]
branch updated

**Comment by jitsukoh** [comment]
@sebvi @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
