### ISSUE TITLE
code table 4.2 and 4.5: additional ocean parameters and levels

### ISSUE THREAD

**Issue by sebvi** [wmo-im/GRIB2#96]
# Branch 
https://github.com/wmo-im/GRIB2/tree/issue96

# Summary and purpose
ECMWF is requesting new ocean parameters and a new type of level.

# Action proposed
The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
ECMWF requires new parameters and a new type of level for an upcoming update of its ocean model (in addition to the parameters proposed during the previous fast track).

The new parameters are:

- sea ice albedo (numeric 0-1)
- vertical eddy diffusivity (m2 s-1)
- sea salt flux (kg m-2 s-1)

The new type of level is 

- ocean level defined by vertical eddy diffusivity difference from near-surface level (m2 s-1)

# Detailed proposal

add in code table 4.2 discipline 10, category 2
| Code | Meaning | Units |
|--|--|--|
| 14 | albedo | numeric (0-1) |

add in code table 4.2 discipline 10, category 3
| Code | Meaning | Units |
|--|--|--|
| 12 | sea salt flux | kg m-2 s-1 |

add in code table 4.2 discipline 10, category 4
| Code | Meaning | Units |
|--|--|--|
| 28 | vertical eddy diffusivity | m2 s-1 |

add in code table 4.5
| Code | Meaning | Units |
|--|--|--|
| 171 | ocean level defined by vertical eddy diffusivity difference from near-surface level (see Note 7) | m2 s-1 |

**Comment by sebvi** [comment]
branch updated

**Comment by jitsukoh** [comment]
@sebvi @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
