### ISSUE TITLE
Normalize notes for templates

### ISSUE THREAD

**Issue by amilan17** [wmo-im/GRIB2#97]
# Purpose

To normalize all notes in published PDF and in GitHub repositories.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/GRIB2/tree/ft21-2](https://github.com/wmo-im/GRIB2/tree/ft21-2) 

*   new notes directory with a compilation of all notes in templateNotes.csv
*   new columns in template tables for note ids, codeTable and flagTable

**Comment by sebvi** [comment]
@amilan17  this is really great! We might need to go through the notes, maybe some of these could be cleverly merged. Or maybe you did that already?

**Comment by amilan17** [comment]
@sebvi -- I did a lot of normalisation already manually. I combined notes when the differences were clearly editorial and the meaning didn't change. However, I'm sure there will be opportunities for further refinement.
